### ISSUE TITLE
Vaadain ProdMode prevent Viritin js download

### ISSUE THREAD

**Issue by gokhanoner** [viritin/viritin#102]
When you set the below parameter on application properteis,  I'm getting error in the image?

    vaadin.servlet.productionMode=true

![image](https://cloud.githubusercontent.com/assets/6715308/9719358/2ed69ba0-558c-11e5-8a01-6319e4ec5a77.png)

For prod, should I take this js and copy it to local ? Actually, I need to because my appl. will run internally, server doesn't have internet access..

**Comment by mstahv** [comment]
Would you re-open this issue in https://github.com/viritin/vwscdn as that is the project related to this. The issue itself should definitely be solved, I have no idea how production mode could affect this. Need to find out...
