### ISSUE TITLE
RichText ignores the custom html classes.

### ISSUE THREAD

**Issue by gokhanoner** [viritin/viritin#105]
```"<td class='fx-right-align'>"``` code inside the RichText doesn't have any effect.  I also see that the class is removed from the code also..

**Comment by mstahv** [comment]
Its a feature :-) Added an example that should help you to override the behaviour.

https://github.com/viritin/viritin/blob/master/src/test/java/org/vaadin/viritin/it/RichTextExample.java

**Comment by gokhanoner** [comment]
OK. Thanks :)
I was setting this on a LabelField. with the last change, label inside the LabelField became a RchText. I used this, I workes for me :)

```
LabelField<String> record = new LabelField<>(String.class, "Record");
record.setLabel(new Label());
record.getLabel().setContentMode(ContentMode.HTML);
```

**Comment by mstahv** [comment]
Hi,

That's perfectly possible, if you can trust the content you are showing on the screen. If you want to use sanitation by the JSOUP library, you can use RichText with LabelField as now in the end of the example.

cheers,
matti
