### ISSUE TITLE
Focus of a Mtable Row

### ISSUE THREAD

**Issue by estkae** [viritin/viritin#107]
Hallo,
i try to get a focus on a Row in a mtable. If click on row it's work. Now i take Filter, the Result is one Row. How can i do an autoselect on this Row.
The mttable has not a Methode select(row).
How can i do this.

**Comment by mstahv** [comment]
Hi, have you tried setValue(T value) ?

The select method from Table should indeed be overridden and the parameter type value should be narrowed to the entity type.

**Comment by estkae** [comment]
Hi thanks a lot,
no i did, have you sample?

**Comment by mstahv** [comment]
// If you want to allow users to select a row as well
        mTable.setSelectable(true);
        
        final Person first = Service.findAll(0, 1).get(0);

        // Sets the "first" person to be selected in the Table
        mTable.setValue(first);
        // this will do the same
        mTable.select(first);
        // ... and a better typed version after Viritin 1.38
        mTable.setSelected(first);

        // Move mouse focus to the table
        mTable.focus();

**Comment by estkae** [comment]
in my mutable Version there are no ränge (min, Max).

public interface VertexRepository extends JpaRepository<Vertex, Long> {
    

	/* A version to fetch List instead of Page to avoid extra count query. */
    List<Vertex> findAllBy(Pageable pageable);
	List<Vertex> findByFamilyStartsWithIgnoreCase(String Family);
	List<Vertex> findRange(int startIndex, int maxResults);
	List<Vertex> findAll();

}
i make a bean:
	private void listVertexRange(int MinInd, int MaxInd) {
		listv.setContainerDataSource(new BeanItemContainer(Vertex.class,
					repo.findRange(MinInd, MaxInd)));

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'vertexRepository': Invocation of init method failed; nested exception is org.springframework.data.mapping.PropertyReferenceException: No property findAll found for type Vertex!

**Comment by mstahv** [comment]
Would you elaborate a bit? Does this still relate to focusing MTable or what? 

I "listv" is your MTable, you should not use setContainerDataSource, but just put your list of beans there with setBeans method.

**Comment by estkae** [comment]
Sorry that is only your sample. I can not Understand why i can not Select a row in a MTable. That's all.
If i look at the property in MTable i can not find findAll(0, 1).
The Filter is working correct ist also a part of a simple of you.
Sorry that all. 
If you want, tell me how can it work.

**Comment by mstahv** [comment]
findAll(0,1) call is just to my mock service and I take first entity from there.

Do you have a proper equals/hashCode methods implemented in your entities? Vaadin selects (includes Table and MTable) use those in object comparison, just like lists and maps in basic Java collections. I'm often using this kind of super class for my entities (with equals/hashCode methods):
https://github.com/mstahv/jpa-addressbook/blob/master/src/main/java/org/example/backend/AbstractEntity.java

**Comment by estkae** [comment]
Thanks a lot, but that helps me not. I think try it with spingdata. It is better explaint.

**Comment by mstahv** [comment]
I don't really get how this relates to Spring Data or what exactly is the issue you have, but I prepared a branch to my Spring Data + Vaadin CRUD example, which should show you how to select (and focus) the first row in a table. The required equals/hashcode for entity is included.

https://github.com/mstahv/spring-data-vaadin-crud/commit/1bc3304d914e0b987ccbfb2f9387a974f614725c
