### ISSUE TITLE
MTable with PagingProvider and CountProvider : NPE when no result

### ISSUE THREAD

**Issue by sebdavid** [viritin/viritin#108]
Hi,

I'm using Viritin 1.37 with Vaadin 7.5.5.
I'm using the following constructor  :
```java
 MTable(LazyList.PagingProvider pageProvider,
            LazyList.CountProvider countProvider)
```
The implementations I supply just return an empty list and a count equals to zero. The fact is that during initialization, the ```dynaClass``` attribute from ```ListContainer``` is never set, and then when no result is returned by the supplied providers, the following method return null (because the list is empty) causing the NullPointerException :
```java
    private WrapDynaClass getDynaClass() {
        if (dynaClass == null && !backingList.isEmpty()) {
            return getDynaClass(backingList.get(0));
        }
        return dynaClass;
    }
```
It seems that the solution would be to supply an additional argument to the MTable constructor : the Class<T>, and then use the following ListContainer constructor at the end :
```java
    public ListContainer(Class<T> type, Collection<T> backingList) {
        dynaClass = WrapDynaClass.createDynaClass(type);
        setCollection(backingList);
    }
```

**Comment by mstahv** [comment]
I guess you set some generated columns (overriding properties) or defined the visible properties? I was able to reproduce this with following code:

        final List<Person> backingList = Service.getListOfPersons(0);
        
        MTable<Person> mTable = new MTable<Person>(
                new LazyList.PagingProvider<Person>() {
                    
                    @Override
                    public List<Person> findEntities(int firstRow) {
                        return backingList.subList(firstRow, 0);
                    }
                },
                new LazyList.CountProvider() {
                    
                    @Override
                    public int size() {
                        return 0;
                    }
                }
        ).withProperties("firstName", "lastName", "email");

**Comment by mstahv** [comment]
I think this  is actually regression since the nested property support was added.

**Comment by mstahv** [comment]
Now properties are of type "Object" if the actual bean type cannot be resolved. I think we should also add setLazyLoad(LazyList.PagingProvider pageProvider,LazyList.CountProvider countProvider) style methods. Then you could instantiate the class with new MTable(Person.class) and then set the lazy loading strategies. Bean type could then be properly inspected with empty backend as well.

**Comment by mstahv** [comment]
I added also helpers. I hope you can try it out with a local snapshot build. Reopen the issue if you still face it or think there are some improvements in the API!

**Comment by sebdavid** [comment]
Hi,
Thank you for the changes. Indeed I defined the visible properties AND set some generated columns !
I will try with a local build later and let you know about the result.
