### ISSUE TITLE
Cookies not storing

### ISSUE THREAD

**Issue by russellhoff** [viritin/viritin#109]
Hi!

I'm trying out BrowserCookies class and I'm not able to store cookies using BrowserCookie.setCookie(ATTR_COOKIE_LOGIN_NAME, pString);

On chrome 45.0.2454.101 m, I can't see the cookie stored. My application is using PushMode manual.

Thanks!!!

**Comment by mstahv** [comment]
I have never used PushMode manual, not sure how it would affect this. Can you prepare a test case so I could repeat this?

**Comment by mstahv** [comment]
I need more information to solve this issue. I tried to reproduce the issue but it works just fine for me. Added the test case to git repository:

https://github.com/viritin/viritin/blob/f00c163f9bbc366b6a7f4aa6b899327ad6539172/src/test/java/org/vaadin/viritin/it/BrowserCookieTestIssue109.java

I'll close this now, but feel free to re-open the issue with more details.
