### ISSUE TITLE
NestedProperty

### ISSUE THREAD

**Issue by wkrix** [viritin/viritin#11]
Hello Matti,

What is the best way to add NestedProperty to your MFieldGroup? 

I think it is the bad way, isnt it? 
binder = BeanBinder.bind(getCompany(), companyDetailsForm);
binder.getItemDataSource().addNestedProperty("address.postcode);

Thanks :)

**Comment by mstahv** [comment]
Hi, returning to the subject as I have been working with various data binding stuff recently. This "works", but all Maddon related bean binding features are not configured?

**Comment by lipodido** [comment]
Hello Matti, 
I have a related question , BeanItemContainer have the property <<addNestedContainerProperty>> so how to accomplish the same with ListContainer ?
Regard (and thank you so much for this great work )

**Comment by mstahv** [comment]
I haven't implemented anything like this, but I think the implementation should be rather easy to add as there is an advanced nested property support in the underlaying commons-beanutils library:
https://commons.apache.org/proper/commons-beanutils/apidocs/org/apache/commons/beanutils/package-summary.html#standard.nested

There should just be some sort of list of additional nested properties to be introduced.
