### ISSUE TITLE
Support for management in case of bi-directional relationships

### ISSUE THREAD

**Issue by jgfrm** [viritin/viritin#111]
In case of editing bi-directional relationships (e.g. via a customized MultiSelectTable) it is necessary to keep track of the objects that must be merged/deleted via a JPA service.
Consider that the following relation is added
```
a->b
```
Bi-directionality supposes that the following should also be added
```
b->a
```
Now suppose that
- b contains a set to relate to a (b can have multiple a's)
- b is added to a via a method of a

Then it is not enough to merge a; b must also be merged in order to store the inverse relationship.

My current approach is that:
- before the form is opened, the presenter builds a representation of the state of the relevant part of the database
- after the form is closed, a plan is calculated that is used to merge/delete objects from the database. This plan ensures that an object is merged precisely once (if necessary)

**Comment by mstahv** [comment]
For this issue there is now these methods:

https://github.com/viritin/viritin/blob/a2ba2e0728a6f0672a21e6f4bcc26d0270863d1e/src/test/java/org/vaadin/viritin/it/MultiSelectTableWithCustomRelationMaintenance.java#L108-L113

Let me know if you need something else.

**Comment by mstahv** [comment]
Hi, I'm closing this for now as it already got released in 1.38. Feel free to reopen or create new issues if this approach is not suitable.
