### ISSUE TITLE
missing code in getNestedPropertyType(...) of ListContainer.java

### ISSUE THREAD

**Issue by psc1952** [viritin/viritin#115]
code needed at line 282:

		if (type.isPrimitive() == true)
		{
			// Vaadin can't handle primitive types in _all_ places, so use
			// wrappers instead. FieldGroup works, but e.g. Table in _editable_
			// mode fails for some reason
			return ClassUtils.primitiveToWrapper( type );
		}

**Comment by mstahv** [comment]
Good catch, thanks!

**Comment by psc1952** [comment]
You're welcome

On Thu, Nov 19, 2015 at 12:39 AM, Matti Tahvonen <notifications@github.com>
wrote:

> Good catch, thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/viritin/viritin/issues/115#issuecomment-157967594>.
>



-- 
Blessings,
Paul

Strive for excellence not perfection,
Work like you don't need the money,
Love like you have never been hurt,
And dance the way you do when no one is looking.
