### ISSUE TITLE
MGrid.sort() does not call SortablePagingProvider.findEntities()

### ISSUE THREAD

**Issue by sebgymn** [viritin/viritin#121]
If a user clicks on a `MGrid` column to sort it, Vaadin will call sort() method of the container (`ListContainer` in this case), but it just does in-memory sorting with `Collections.sort()` whereas it should call `SortablePagingProvider.findEntities()` if it was constructed with a `SortablePagingProvider`.

Two ways I see this can be fixed: 

1. By subclassing `ListContainer` to `SortableListContainer` and linking sort() method call to `SortablePagingProvider.findEntities()`.
2. Adding a custom `SortListener` method to `ListContainer` which lets a listener to change sorting behavior. Sol. 1 will be better, IMO.

**Comment by mstahv** [comment]
Good catch, I think I actually noticed when drafting the first version of MGrid that sorting was not fully functional in MGrid/SortablePagingProvider, but had completely forgotten the issue. I remember it looked tricky at that point and it sure was not the most trivial solution to solve, but I hope it is now tackled.

I went with one ugly instanceof check in ListContainer and some other checks and row cache invalidation. Do you have a change to test this solution (using a local SNAPSHOT build from master) in your real world use case? I just drafted an simple test case to the project. Thanks in advance!

**Comment by nrant** [comment]
Matti - I not sure this has fixed the issue.

Using viritin 1.42 - when the header is clicked to sort on the column - the table does not appear to refresh and it doesn't invoke SortablePagingProvider.findEntities().
I also tried 
`grid.addSortListener(new SortListener() {			
			@Override
			public void sort(SortEvent event) {
				grid.lazyLoadFrom(provider.getSortablePagingProvider(), provider.getCountProvider());				
			}
		});`
.. but when SortablePagingProvider.findEntities() is invoked the sort parameter is blank so I'm assuming when Grid.lazyLoadFrom is called - existing sort info is cleared, or not propagated?

To get around this I'm passing in the SortOrder into a new SortablePagingProvider in a SortListerner and calling lazyLoadFrom
i.e.
`event -> {SortOrder so = event.getSortOrder().get(0);
			grid.lazyLoadFrom(provider.getSortablePagingProvider(so
					.getPropertyId().toString(),
					so.getDirection().equals(SortDirection.ASCENDING)),
					provider.getCountProvider());
			grid.cancelEditor();
		}`
I'm using a similar approach with filters above each column to provide a multi param filtering sorting paging lazy loading grid. I took inspiration from the lazy combo
It would be good if the sorting was internal to the mgrid & sortableLazyList

**Comment by mstahv** [comment]
It should be fixed. See this usage example:

https://github.com/viritin/viritin/blob/7934a94f5390029de7bbf4a26e559667b96293cf/src/test/java/org/vaadin/viritin/it/MTableLazyLoadingWithSorting.java

Instead of sorting the list you should just query your backend with the relevant parameters. No need to add sort listeners or resetting the providers.

cheers,
matti

**Comment by nrant** [comment]
Matti
Taking code directly from https://github.com/viritin/viritin/blob/master/src/test/java/org/vaadin/viritin/it/GridLazyLoadingAndSorting.java & https://github.com/viritin/viritin/blob/master/src/test/java/org/vaadin/viritin/it/MTableLazyLoadingWithSorting.java

Issue 1
MTable displays the sorted data when header is clicked
MGrid does not display the sorted data when header is clicked - sorted data is only displayed if you then scroll the grid past the "cached" page data - which then forces new page call to the service with a new page and the correct sort order.

Issue 2
grid.lazyloadfrom(page-provider, count-provider) - (Re-setting the providers).... current sort order on the grid is not propagated to the new page provider. 
Use case for this is a multi column filtering using lazy loading - (replicating this - http://demo.vaadin.com/commit-browser/) - when a filter text changes, provider has to be re-set with new filtering parameters... ala lazycombo.

The only way I could get it working with grid is to add sort listener and reset provider manually adjusting the sort order as I showed above.

hope that explains better
cheers
Nick

**Comment by mstahv** [comment]
For me the GridLazyLoadingAndSorting test works just fine so I'd guess there is something different in our environment. Which version of Vaadin do you have in your project?

I think setting filtering should be possible as well (by just using the same filter aware providers), but you'll have to manually call refreshRows() method after your filters change. I could maybe replicate the commit-browser example as a test case/example at some point.

**Comment by nrant** [comment]
Vaadin 7.6.1
viritin 1.42

Ok - I've just reverted back to vaadin 7.5.10 and the grid sort works as expected :-). 
Vaadin 7.6.0 & 7.6.1 don't work... something has changed?
Re:filtering - Ahhh... I'll try refreshRows()

**Comment by mstahv** [comment]
I just tried with 7.6.1 and it indeed seems to be broken :-( Damn. I'd bet it was working with 7.6 series as well, but I might have lost my focus. The underlaying refreshCache method do get called, but I guess the behaviour has somehow changed and it really don't refresh content properly.

**Comment by mstahv** [comment]
Fixed in https://github.com/viritin/viritin/commit/d4aecf68fc50352c6a84db4412ac4d4ee6cf8c85

7.6 series apparently needs to receive itemsetchangeevent as well, resetting the cache only don't work.
