### ISSUE TITLE
Cannot clear selection on LazyComboBox

### ISSUE THREAD

**Issue by raehalme** [viritin/viritin#122]
I'm using `LazyComboBox` to pick a value from the database (with ~3000 options). 

If I pick a value from the second page, for example the 10th option (as the combobox shows 9 options at a time), and then try to clear the selection by picking the first (ie. `null`) option, the latter selection does not propagate a value changed event. 

If I reopen the combobox and choose any option from the first page, and then try to clear the selection by picking the first option, the value is set to `null` properly.

Any idea what's going on here?

**Comment by mstahv** [comment]
Looks like a bug to me. Not quite sure if this is an issue in Viritin or in the core ComboBox implementation though. Which version of Vaadin are you using?

**Comment by raehalme** [comment]
We're using Vaadin 7.5.8.

**Comment by mstahv** [comment]
I looked this a bit more and I think you are facing the same (or closely related) issue as described here:

https://dev.vaadin.com/ticket/19221#ticket

7.6 don't seem to fix anything on this area yet :-(

**Comment by mstahv** [comment]
Finally in in 7.7.0, sometimes it just takes time, software development...

https://dev.vaadin.com/ticket/19221

**Comment by raehalme** [comment]
Now it seems to work as intended! That's awesome, thanks!
