### ISSUE TITLE
Mgrid is not displayed when LazyList.CountProvider returns zero

### ISSUE THREAD

**Issue by alkhimistta** [viritin/viritin#124]
I´m using `LazyList` in combination with MGrid. When `LazyList.CountProvider` returns zero, MGrid is not displayed. If I try to use MGrid method `setColumnOrder`, throws an exception `Grid does not contain column for property`.

**Comment by mstahv** [comment]
We should add similar lazyLoadFrom methods to MGrid as there is in MTable:

https://github.com/viritin/viritin/blob/master/src/main/java/org/vaadin/viritin/fields/MTable.java#L139-L191

Then you could construct the table with the explicit type as parameter and allow empty tables. Want to try doing this?

**Comment by alkhimistta** [comment]
I added the following method to MGrid:

```java
public MGrid<T> lazyLoadFrom(LazyList<T> lazyList) {
    	setRows(lazyList);
        return this;
}
```

This is my test code:

```java
LazyList<TestBean> lazyList = new LazyList<TestBean>(new LazyList.PagingProvider<TestBean>() {
  @Override
  public List<TestBean> findEntities(int firstRow) {
    return new ArrayList<TestBean>();
  }
}, new LazyList.CountProvider() {
  @Override
  public int size() {
    return 0;
  }
});

MGrid<TestBean> mGrid = new MGrid<TestBean>(TestBean.class);
mGrid.lazyLoadFrom(lazyList);
```
This code throws the following exception:

Found at least one column in Grid that does not exist in the given container: testcolumn1 with the header "Testcolumn1"

**Comment by mstahv** [comment]
I think I nailed the issue, if you use the constructor with entitytype and assign the lazy loading strategy with one of the lazyLoadFrom methods. Can you try my fix in your use case? The project should build with just mvn install.

**Comment by alkhimistta** [comment]
Ok, it´s works!!

I see you have added methods to sortable lists but they are not working; the listener to update rows is not defined. However, although the listener is set, changing the order does not call SortablePagingProvider.findEntities()

**Comment by mstahv** [comment]
Thanks, that should be now fixed as well.
