### ISSUE TITLE
TypedSelect as OptionGroup doesn't select value at page.

### ISSUE THREAD

**Issue by diogolopes** [viritin/viritin#130]
I'm trying to use TypedSelect, the method selectFirst() and also method setValue( ); do not repaint the component.

The getValue() returns the correctly object, but the designer of option group do not check the right value.

My code :

public enum AccountType {
    BNS("BNS", "B"), EGL("EGL", "E"), COSIF("COSIF", "C");
}

private TypedSelect<AccountType> accountTypeTypedSelect = new TypedSelect<AccountType>(AccountType.values()).withSelectType(OptionGroup.class);
.
.
.
.
.

accountTypeTypedSelect.selectFirst();
or
accountTypeTypedSelect.setValue(AccountType.BNS);

And the displayed page do not select the value.
But the accountTypeTypedSelect.getValue() have it.

Could you help me ? Thanks.

**Comment by mstahv** [comment]
Hi

Would you share all related classes?  Can't see what is exactly wrong in your code, would need to use debugger to see what is going on.

This works for me:

        TypedSelect<AddressType> types = new TypedSelect<>()
                .withSelectType(OptionGroup.class)
                .setOptions(AddressType.values()); // AddressType is an enum
        types.selectFirst();
        return types;

**Comment by diogolopes** [comment]
Hi, I use Reindeer theme and the problem was in my css file to customize the optionGroup to horizontal.

Thanks a lot mstahv.
