### ISSUE TITLE
MBeanFieldGroup.isValid() always returns false

### ISSUE THREAD

**Issue by hbiloo** [viritin/viritin#131]
Hi,

I've a very simple form using the `org.vaadin.viritin.form.AbstractForm` which contains 3 fields that are bound to a JPA entity `Member`. When the form is initialised, the values are displayed in the GUI. A simple print to the console shows these values:
```
2016-01-27 10:43:45.424  INFO 13066 --- [tp2016430564-16] n.d.view.member.MemberForm2      : Initials: L
2016-01-27 10:43:45.425  INFO 13066 --- [tp2016430564-16] n.d.view.member.MemberForm2      : Middle name: van
2016-01-27 10:43:45.425  INFO 13066 --- [tp2016430564-16] n.d.view.member.MemberForm2      : Last name: Gaal
```

If I do or not change one of these field values and press the "Check validation" button, either `fieldGroup.isValid()` and `fieldGroup.isModified()` return false. This of course results in disabling the save button.

Is here something that I'm doing wrong?

### Log after hitting the "Check validation" button:
```
2016-01-27 10:55:07.482  INFO 13066 --- [tp2016430564-16] n.d.view.member.MemberForm2      : Form isValid(): false
2016-01-27 10:55:07.496  INFO 13066 --- [tp2016430564-16] n.d.view.member.MemberForm2      : FieldGroup isValid(): false
2016-01-27 10:55:07.496  INFO 13066 --- [tp2016430564-16] n.d.view.member.MemberForm2      : FieldGroup isModified(): false
2016-01-27 10:55:07.530  INFO 13066 --- [tp2016430564-16] n.d.view.member.MemberForm2      : validation.initials.required
2016-01-27 10:55:07.530  INFO 13066 --- [tp2016430564-16] n.d.view.member.MemberForm2      : validation.last.name.required
2016-01-27 10:55:07.530  INFO 13066 --- [tp2016430564-16] n.d.view.member.MemberForm2      : getConstraintViolations() size: 2
2016-01-27 10:55:07.530  INFO 13066 --- [tp2016430564-16] n.d.view.member.MemberForm2      : Invalid value: null | Message: validation.initials.required | Path: initials

2016-01-27 10:55:07.530  INFO 13066 --- [tp2016430564-16] n.d.view.member.MemberForm2      : Invalid value: null | Message: validation.last.name.required | Path: lastName
```

### MemberForm2
```java
@Slf4j
public class MemberForm2 extends AbstractForm<Member> {
    final MBeanFieldGroup<Member> fieldGroup;

    @PropertyId("initials")
    private MTextField initials = new MTextField()
            .withWidth(100.0f, Unit.PIXELS)
            .withInputPrompt("Initials");

    @PropertyId("middleName")
    private MTextField middleName = new MTextField()
            .withWidth(100.0f, Unit.PIXELS)
            .withInputPrompt("Middle");

    @PropertyId("lastName")
    private MTextField lastName = new MTextField("Last")
            .withFullWidth()
            .withInputPrompt("Last");

    public MemberForm2(final Member member) {
        fieldGroup = setEntity(member);
        log.info("Initials: {}", member.getInitials());
        log.info("Middle name: {}", member.getMiddleName());
        log.info("Last name: {}", member.getLastName());
    }

    private void initFields() {
        initials = new MTextField()
                .withWidth(100.0f, Unit.PIXELS)
                .withInputPrompt("A.");
        middleName = new MTextField()
                .withWidth(100.0f, Unit.PIXELS)
                .withInputPrompt("Middle");
        lastName = new MTextField("Last name")
                .withFullWidth()
                .withInputPrompt("Bakker");
    }

    @Override
    protected Component createContent() {
        return new MVerticalLayout(
                new MFormLayout(
                        newButton(),
                        new MHorizontalLayout(initials, middleName).withCaption("Name"),
                        lastName
                ).withMargin(false).withFullWidth(),
                getToolbar()
        ).withMargin(new MMarginInfo(false, true)).withFullWidth();
    }

    private Button newButton() {
        final Button button = new Button("Check validation");
        button.addClickListener(new Button.ClickListener() {
            @Override
            public void buttonClick(Button.ClickEvent event) {
                log.info("Form isValid(): {}", isValid());
                log.info("FieldGroup isValid(): {}", fieldGroup.isValid());
                log.info("FieldGroup isModified(): {}", fieldGroup.isModified());

                final Collection<String> beanLevelValidationErrors = fieldGroup.getBeanLevelValidationErrors();
                if (CollectionUtils.isNotEmpty(beanLevelValidationErrors)) {
                    for (String beanLevelValidationError : beanLevelValidationErrors) {
                        log.info(beanLevelValidationError);
                    }
                }

                final Set<ConstraintViolation<Member>> constraintViolations = fieldGroup.getConstraintViolations();
                log.info("getConstraintViolations() size: {}", constraintViolations.size());

                for (ConstraintViolation<Member> constraintViolation : constraintViolations) {
                    log.info("Invalid value: {} | Message: {} | Path: {}\n",
                            constraintViolation.getInvalidValue(),
                            constraintViolation.getMessage(),
                            constraintViolation.getPropertyPath()
                    );
                }
            }
        });
        return button;
    }
}
```

### Member
```java
@Data
@Entity
@Table(name = "member")
public class Member implements FriendlyIdentifiable, Serializable {
    private static final String MEMBER_CODE = "MEM";

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String reference;

    @NotNull(message = "validation.initials.required")
    private String initials;

    private String firstName;
    private String middleName;

    @NotNull(message = "validation.last.name.required")
    private String lastName;
}
```

**Comment by mstahv** [comment]
Hi, I copied your sources to the project with same minimal changes and the code seems to work just fine to me. See the changes above.

When an entity with require fields filled in passed to for, Save is initially disabled (as there are no modifications). Becomes active if you change some field, unless some of the field don't pass validation (when we don't want users to click save).

Can you give any more details if you think there is some bug? Maybe a small example project where I could reproduce the issue?

**Comment by hbiloo** [comment]
Hi Matti,

Thanks for your comment and quick response. Just wondering what does the "Check validation" button print to your console after making some valid changes in one of the fields? In my case as already mentioned in the issue, the ```fieldGroup.isValid()``` returns false and the constraint violations set is not empty even when those fields are valid.

Clicking on the save button displays the right state of the entity in my case (valid values i.s.o. ````null````s).

**Comment by mstahv** [comment]
Jan 27, 2016 5:56:10 PM [org.vaadin.viritin.it.issues.Issue131]  invoke
INFO: Form isValid(): true
Jan 27, 2016 5:56:10 PM [org.vaadin.viritin.it.issues.Issue131]  invoke
INFO: FieldGroup isValid(): true
Jan 27, 2016 5:56:10 PM [org.vaadin.viritin.it.issues.Issue131]  invoke
INFO: FieldGroup isModified(): false

So the isModified() is indeed false and that is probably what looks weird to you. isModified is coming form the super implementation in Vaadin and I didn't want to override its implementation, and it kind of works as the FieldGroup is in "non-buffered" mode. Try isBeanModified() instead, I think that works as you'd expect. That is cleared when bean is bound to form or when save/reset button is clicked. 

I should add some javadocs for isBeanModified and I also should probably start writing a manual for Viritin and all its features.

**Comment by mstahv** [comment]
Addition to the above, the built in Save/reset buttons state depends on isBeanModified as well.

**Comment by hbiloo** [comment]
The method ```isBeanModified()``` returns indeed ```true```. This results in enabling the Cancel button. But because the form is not valid in my case (even if the values are not blank), the Save button stays disabled. Also I'm getting 2 constraint violations which say that the value of ```initials``` and ```lastName``` fields is ```null```.

Maybe the values of the entity are not passed to the ```MBeanFieldGroup```. I'll try to make a small project where I can reproduce this behaviour.

**Comment by mstahv** [comment]
For me the values are passed just fine for the backing object. I have no idea what is the problem with with your validation. An example project is a good idea indeed.

**Comment by hbiloo** [comment]
Was forgotten to close this issue. The problem was in the way my entity was fetched. Adopted the service method which passes the entity to the view -> form, and it worked.

:+1: thanks.
