### ISSUE TITLE
LazyComboBox not displaying selection after re-opening dropdown 

### ISSUE THREAD

**Issue by nrant** [viritin/viritin#132]
LazyComboBox configured with a spring data pageable repository.
Start typing search criteria and combo dropdown has values.
Select value - dropdown closes - selected value displayed. :-)

Either: click dropdown button and then move focus to another control
Or: click on combobox and delete visible entry and then move focus to another control

ComboBox does not clear the original selected value or remove the original selected value. Either blank is displayed or the input prompt and no ValueChangeEvent is raised.

Registering a Blur event on the underlying combo - Not able to identify that the "displayed" value has changed - only that the original selected value is still valid. Even a call to setValue and repaint makes no difference.

I suspect it's some how related to https://github.com/viritin/viritin/issues/66 & https://dev.vaadin.com/ticket/19221#ticket ?
Have raised this as a different issue as it's a slightly different use case

Have tried setScrollToSelectedItem(true & false) on the underlying combobox but nothing seems to correct the issue. It's a real shame as this severely affects usability of the control.

**Comment by mstahv** [comment]
I think it really is related to those other issue. This needs to be fixed in Vaadin. I already submitted a patch a while ago, but is still not in releases as there are "other related changes" going on :-(

**Comment by samie** [comment]
What Vaadin version are you using?

**Comment by nrant** [comment]
Vaadin 7.5.5
Viritin 1.41

**Comment by mstahv** [comment]
I had to re-read the issue, are you trying to remove the currently selected value? 

IIRC the original ComboBox in Vaadin does check if value is in container any more when removed, but in LazyComboBox this cannot be done as it is potentially a really expensive operation.

The Vaadin version you are using is pretty old, you could try 7.5.10 (the latest in 7.5 series) or the latest 7.6.1.

**Comment by nrant** [comment]
Not quite...
After selecting an item in the LazyComboBox - the selected value is displayed as expected.
Then either...
Click on the combobox drop down button - popup opens but is empty (as expected).
Then move focus away from the combobox - input prompt is displayed.
Or
Click on the combobox text entry and "delete" the text.
Then move focus away from the combobox - blank is displayed.

The original selected value is still returned from getValue() (understandable as the user has not selected a new value - but... the combobox display doesn't match the held value). 

I'll try upgrading the vaadin version - I'd not realised it was that far behind - although I think i was restricted by the vaadin4spring security stuff I'm also using.

**Comment by nrant** [comment]
I've just upped the vaadin to 7.6.1 - same behaviour unfortunately.
This is with setNullSelectionAllowed(false & true).

The issue for me is that the control displays the input prompt or blank but the getValue() returns the originally selected value.

**Comment by nrant** [comment]
Ok guys... after going round in circles for the last couple of days (hence raising this issue) .. i'm not entirely convinced of my observations and think some of them may be due to additional complexity in my own code / services.
I'm going to strip everything back and retest tomorrow... I'll report back and / or close this issue after that

**Comment by nrant** [comment]
Right - Vaadin 7.6.1 Viritin 1.41 - Simple test using the setup from LazyComboBoxUsageSample.java added into a view with UIScope.

**Use case 1**
Enter "id=10" & select Person(id=10).
Re-Open dropdown (data = page 1 including id=10 which is selected in dropdown) then move focus away from combo without selecting anything.
Dropdown closes - combo displays Person(id=10).
getValue() returns Person(id=10)
Change views and then return to this view - combo displays Person(id=10)

This behaviour is as expected :-)

**Use case 2**
Enter "id=11" & select Person(id=11).
Re-Open dropdown (data = page 1 not the filtered page) then move focus away from combo without selecting anything.
Dropdown closes - combo displays input prompt - no change event is fired.
getValue() returns Person(id=11)
Change views and then return to this view - combo displays Person(id=11)
Select combo text field
Move focus away from combo - combo displays input prompt.
Change views and then return to this view - combo displays Person(id=11)
getValue() returns Person(id=11)

This behaviour is not as expected -
The end user thinks item has been de-selected when it actually hasn't.
If getValue() !-= null then Combobox should display the value of getValue() after any interaction has finished (i.e. onBlur)

Assuming this is related to https://github.com/viritin/viritin/issues/122 as well as the other ticket above.

**Comment by mstahv** [comment]
FINALLY, fixed in 7.7.0!

https://dev.vaadin.com/ticket/19221
