### ISSUE TITLE
MTable constructor for empty list

### ISSUE THREAD

**Issue by fphilip** [viritin/viritin#134]
`    public MTable(Class<T> type, LazyList.PagingProvider pageProvider,
            LazyList.CountProvider countProvider) {
        this(new LazyList(type, pageProvider, countProvider, DEFAULT_PAGE_SIZE));
    }`

because when the collection is empty, the scan of properties not ocurr

**Comment by mstahv** [comment]
Adding constructors like those could be handy indeed. Until those are added, you can use

    table = new MTable<>(YourEntity.class);
    table.lazyLoadFrom(....);
