### ISSUE TITLE
Handling of nested properties in MGrid can be improved

### ISSUE THREAD

**Issue by elomagic** [viritin/viritin#138]
Hi,
you written a very great AddOn but...
...using nested properties like the way the code do in the class `MTableWithNestedProperty` for class `MTable` by using the method `withProperties` don't work with the `MGrid` class and can be improved.
The current workaround is to add the nested properties manually to the `ListContainer` like these way:

```
ListContainer container = (ListContainer)grid.getContainerDataSource();
container.setContainerPropertyIds(beanPropertyIds);
grid.withProperties(beanPropertyIds);
```

Maybe you can add this feature into the `MGrid` like 'MTable' already do. This would simplify the code handling.

Regards, Carsten

**Comment by mstahv** [comment]
Yep, definitely needs to be added. I'll try to find a moment for Viritin, but will be still quite busy for the next week. If you want to contribute this, just let me know you are working on this and post me a pull request when you are ready.

**Comment by mstahv** [comment]
That was pretty easy, can you try with a build from master if the solution suits for you?

**Comment by elomagic** [comment]
It works successfully in the release 1.46. Thx
