### ISSUE TITLE
VaadinLocale uses @since 1.7 methods, but pom states 1.6 requirements for sorces and target

### ISSUE THREAD

**Issue by maslovalex** [viritin/viritin#139]
`VaadinLocale.getLocale`  invokes `Locale.forLanguageTag` 
`VaadinLocale.setLocale`  invokes `Locale.toLanguageTag` 

Both methods are marked as `@since 1.7` in `java.util.Locale`.

I think it would be  reasonable to change `maven-compiler-settings` to 
```xml
<configuration>
     <source>1.7</source>
     <target>1.7</target>
</configuration>
```
At least to avoid errors when compiled with JDK 6.

**Comment by mstahv** [comment]
I wonder if there was an easy way to make that really 1.6 compatible? About 5% is using 1.6, so its not critical to just to drop support for Java 6 though.

**Comment by maslovalex** [comment]
Based on what I see in `VaadinLocale` it is possible to store just `Locale` object in `VaadinSession` (which would be 1.6 compatible), but maybe there is a reason to do Locale->Tag:String->Locale magic between `setLocale` - `geLocale`. Not SO familiar with Vaadin or Locale to be sure.

IMHO dropping 1.6 is acceptable solution.
I guess you know better about 1.6 use among Vaadin "big" customers (sometime it is quite a Process for those ones to move to the next java). Maybe that's the reason why core Vaadin keeps `1.6` in `build.properties`...

**Comment by mstahv** [comment]
Went for 1.7 as it is such a safe and easy solution. If somebody still needs 1.6 Java, feel free to find a workaround for this and send in a pull request.
