### ISSUE TITLE
MGrid Paged CRUD data - add new item - Cannot invalidate ListContainer without reinitialise 

### ISSUE THREAD

**Issue by nrant** [viritin/viritin#141]
Hi Matti
Typical paged crud application - where entityId is created by backend - MGrid showing current data and button to add new data via form.
When new entity is added to backend - there is no way to invalidate the current ListContainer cache without reinitialising / rebuilding the MGrid via lazyLoadFrom. MGrid.RefreshRows() only works for visible rows (i.e. after update)

Is this the expected way?
Would it make more sense to expose ListContaniner.fireItemSetChange() to MGrid and have a MGrid.refreshContainer() method?

cheers
Nick

**Comment by mstahv** [comment]
Hmm, maybe, just maybe, should actually also call ListContaniner.fireItemSetChange() from the refreshRows() method. Do you think that would have some complications?

**Comment by nrant** [comment]
That will certainly fix it ;-) 
Only issue i can think of is MGrid.refreshRows is now less efficient for crud update scenario. 
i.e. select row on grid, click edit, opens form, edit, save to backend, close form, refresh rows - previously this refreshed in-memory visible rows - (very efficient for this scenario).... Obviously now it will reload the container meaning a call to the provider.
Only other option would be 2 methods? refreshVisibleRows & refreshRows ?

**Comment by mstahv** [comment]
We seem to thing in same way :-) There actually already is refreshVisibleRows like you suggested, see the change I did.

BTW. There is also refreshRow(T) method that can update individual rows.

**Comment by nrant** [comment]
Ah.... I didn't read all the changes correctly. Those changes should cover all scenarios now.
