### ISSUE TITLE
Declaring functional interfaces

### ISSUE THREAD

**Issue by daniel-salas** [viritin/viritin#143]
Many of the interfaces existing in Viritin, such as MValueChangeListener or SimpleColumnGenerator, would benefit of a further reduction of boilerplate code just by setting them as functional interfaces.

**Comment by mstahv** [comment]
Aren't those functional interfaces already? I use them all the time with lambdas and method references. Do you mean just adding the the annotation? That would require dropping support to Java7 altogether.

**Comment by daniel-salas** [comment]
You're completely right. The reason I couldn't use them is that my IDE got corrupted (just realized it yesterday).

My apologies for taking your time, and keep up the awesome job!

**Comment by mstahv** [comment]
Hi Daniel, will you still modify your rating in vaadin.com/directory ?
