### ISSUE TITLE
TypeSelect.getItemIcon

### ISSUE THREAD

**Issue by f92dev** [viritin/viritin#151]
It could be useful to have a method `TypeSelect.getItemIcon(T)` maybe together with an interface IconGenerator like the existent CaptionGenerator to set an item icon.
This is needed expecially in the LazyComboBox since the wrapped ComboBox cannot be overridden.

**Comment by mstahv** [comment]
Thanks for the idea!

The feature will be in soon to be built version, but core Vaadin has an issue that prevents showing the icon for selected items, if the item is not on the first page. Need to create a ticket about that to dev.vaadin.com....
