### ISSUE TITLE
After MTable.setBeans(...)  , mTable.getValue() is null 

### ISSUE THREAD

**Issue by smallufo** [viritin/viritin#153]
I want to do some in-place editing with MTable , So I modify this code to MTable
[https://gist.github.com/canthony/6669418](https://gist.github.com/canthony/6669418)

And use my SortableLazyList<> lazyList to fill the MTable : 

<pre>
  public void reload() {
    mTable.setBeans(lazyList);
    mTable.sort(new Object[]{"id"} , new boolean[]{false});
  }
</pre>

But when deal with  : [mTable.getValue()](https://gist.github.com/canthony/6669418#file-exampletableeditingui-java-L146)

It returns null .

I have to change my reload() to this : 
<pre>
  public void reload() {
    lazyList.stream().forEach(item -> {
      mTable.addItem(item);
    });  
    mTable.sort(new Object[]{"id"} , new boolean[]{false});
  }
</pre>

To make it work.

Is it a bug ? 
Environment : 
viritin 1.47
Spring boot 1.3.3

**Comment by mstahv** [comment]
It is not a bug. getValue() is a method of AbstractSelect, super class of Table. It will return null unless setValue is called or a user has selected a row on the client side (and the table is selectable).

You usage of SortableLazyList seems bit odd. You should define the default sort order in the implementation of the interface you pass for your SortableLazyList. You shouldn't need to call sort separately.

**Comment by smallufo** [comment]
Sorry to bother again.

 If I want to do in-place-editing , it seems I have to do mTable.addItem() , right ?
[The demo setValue column by column](https://gist.github.com/canthony/6669418#file-exampletableeditingui-java-L213)

And  `mTable.setBeans(lazyList)` won't do it (just for display)  , right ?

**Comment by mstahv** [comment]
Hi,

I have never tried inplace editing with MTable/LazyList. I rarely see that as a good approach UX wise and most often use a separate form to edit entities.

You just use setEditable(true)? Can you share the whole project you are working on? Then it might be easier to help you or find solutions for issues.

cheeers,
matti
