### ISSUE TITLE
Content of generated column disappears when using MList with Lazy Pageable

### ISSUE THREAD

**Issue by RookieGuy** [viritin/viritin#161]
I have an MTable with a Pageable List on viritin 1.47. When scrolling up and down through the result set, the List loads the new values and displays them. For more than e.g. 3k elements, if I scoll down using the scrollbar and let the component load a complete page of items and then scroll up using the mousewheel the autogenerated column is not rendered anymore. 
I tried it with the SimpleColumnGenerator and list.addGeneratedColumn, here is the code of the pretty simple class it is based on one of the examples.
I hope it is the right place to post this to and this is a bug, maybe I forgot something in the code below and should rather ask at stackoverflow.
Thanks for the great library!   

`@SpringUI(path="words")@Theme("valo")public class WordEditor extends UI {

	@Autowired
	private WordRepository repository;
	
	private MTable<Word> list = new MTable<>(Word.class)
			.withProperties("word", "language.name")
			.withColumnHeaders("Word", "Language")
			.setSortableProperties("word", "Language")
			.withGeneratedColumn("Exclude", new SimpleColumnGenerator<Word>() {
				@Override
	            public Object generate(Word word) {
					
					boolean cbValue = false;
					if (word != null) {
						cbValue = word.isExclude();
					}
	                CheckBox cb = new CheckBox(null, cbValue);
	                cb.addValueChangeListener(
	                		e -> {
	                			if (word == null) return;
	                			
	                			word.setExclude(Boolean.TRUE.equals(cb.getValue()));
	                			repository.save(word);
	                		});
	                return cb;
	            }
	        })
			.withFullWidth();

	
	private Button delete = new ConfirmButton(FontAwesome.TRASH_O,
			"Are you sure you want to delete the entry?", this::remove);
	
	private TextField searchBox = new MTextField();
	
	private String filterSearchTerm = null;
	
	@Override
	protected void init(VaadinRequest request) {

		setContent(
				new MVerticalLayout(
						new MHorizontalLayout(delete, searchBox),
						list
						).expand(list)
				);
		searchBox.addTextChangeListener(this::searchChanged);
		
		listEntities();
		list.addMValueChangeListener(e -> adjustActionButtonState());
	}

	private void searchChanged(TextChangeEvent tce) {
		
		filterSearchTerm = tce.getText();
		listEntities();
	}
	
	protected void adjustActionButtonState() {
		boolean hasSelection = list.getValue() != null;
		delete.setEnabled(hasSelection);
	}

	static final int PAGESIZE = 45;

	private void listEntities() {
		// A dead simple in memory listing would be:
		// list.setBeans(repo.findAll());

		// Lazy binding with SortableLazyList: memory and query efficient 
		// connection from Vaadin Table to Spring Repository
		// Note that fetching strategies can be given to MTable constructor as well.
		// Use this approach if you expect you'll have lots of data in your 
		// table.
		
		SortableLazyList<Language> lazyList;
		CountProvider countProvider;

		countProvider = () -> (int)repository.count();
		lazyList = new SortableLazyList<>(
				// entity fetching strategy
				(firstRow, asc, sortProperty) -> repository.findAllBy(
						new PageRequest(
								firstRow / PAGESIZE, 
								PAGESIZE,
								asc ? Sort.Direction.ASC : Sort.Direction.DESC,
										// fall back to id as "natural order"
										sortProperty == null ? "id" : sortProperty
								)
						),countProvider, PAGESIZE);

		list.setBeans(lazyList);
		adjustActionButtonState();
	}

`

**Comment by maxschuster** [comment]
Are the equals and hashCode methods of the Word entity implemented correctly? So that if the Word is fetched from the database a second time it's equal to to the first Word instance?

**Comment by mstahv** [comment]
equals and hashCode would be my guess as well. Could you share your Word entity as well?

This is how I typically implement equas/hashCode in my entities:
https://github.com/mstahv/jpa-invoicer/blob/master/src/main/java/org/example/backend/AbstractEntity.java

**Comment by mstahv** [comment]
I tried to replicate the issue, but without success. Please share the implementation of your Word entity or let us know if it was the issue with equals/hashCode implementations.

**Comment by RookieGuy** [comment]
Dear Max & Matti,
I missed the hashCode and equals implementation, thanks! At first sight it's not that clear for a beginner like me that this is actually required, I didn't think of the object being reloaded by the persistence layer.
So here is the entity with the implementation from the example. 

    @Entity
    @Table(uniqueConstraints=@UniqueConstraint(columnNames={"language", "word"}))
    public class Word implements Frequency {

	public static final int WORD_MAXLEN = 40;
	
	@ManyToOne 
	@JoinColumn(name="language")
	private Language language;
	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Long id;
		
	@Column(length=WORD_MAXLEN)
	private String word;

	
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if(this.id == null) {
            return false;
        }

        if (obj instanceof Word && obj.getClass().equals(getClass())) {
            return this.id.equals(((Word) obj).id);
        }

        return false;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 43 * hash + Objects.hashCode(this.id);
        return hash;
    }
	
	//[..]
    }`
