### ISSUE TITLE
Javadocs published, please

### ISSUE THREAD

**Issue by phansson** [viritin/viritin#164]
To make it easier to explore Viritin please consider this blog by your Vaadin colleague:

https://vaadin.com/blog/-/blogs/host-your-javadoc-s-online-in-github

**Comment by mstahv** [comment]
I'm not a big fan of that method as the javadocs are published to maven repository anyways. I guess most users use them through that (via IDE). You can also find them online:

http://demo.vaadin.com/javadoc/org.vaadin/viritin/1.47/

The last part in url is the version. With the service you can find any javadocs in the Directory's maven repository.
