### ISSUE TITLE
SortablePagingProvider allows sorting by single property only

### ISSUE THREAD

**Issue by mbruch** [viritin/viritin#173]
Grids allow to sort by multiple columns (by pressing Shift when clicking on a grid header). However, org.vaadin.viritin.SortableLazyList.SortablePagingProvider.findEntities(int, boolean, String) does only pass the first sorting property to the provider.

It would be awesome if the interface would get all sorting information from the Grid.

**Comment by viydaag** [comment]
Yes indeed, it would be a great improvement

**Comment by mstahv** [comment]
I only tested the with a dummy implementation, could somebody test if this works (with a local SNAPSHOT build) before I cut a new release?

**Comment by viydaag** [comment]
I have tested it with a local SNAPSHOT and a database. It works with both calling 
`grid.sort(Sort.by("prop1",` SortDirection.ASCENDING).then("prop2", SortDirection.ASCENDING));`
and sorting by clicking the grid header with shift key.
