### ISSUE TITLE
MTable and MGrid setRows/lazyLoadFrom does not obey current sorting property

### ISSUE THREAD

**Issue by hofmanndavid** [viritin/viritin#184]
The next code does not obey sorting, it only sorts after you touch the header of the grid, am I missing something?

```
MGrid<Product> grid = new MGrid<>(Product.class);
grid.sort(Product.ID, SortDirection.ASCENDING);
grid.setRows(new SortableLazyList(safep, pageSize));
```

Even using the recommended methods in the wiki it doesn't work

```
grid = new MGrid<>(Product.class);
grid.sort(Product.ID, SortDirection.ASCENDING);
grid.lazyLoadFrom((SortableLazyList.SortableEntityProvider)safep, safep, pageSize);

/// or the table version
MTable<Product> table = new MTable<>(Product.class);
table.setSortContainerPropertyId(initialSorting.getPropertyId());
table.setSortAscending(initialSorting.getDirection() == SortDirection.ASCENDING);
table.lazyLoadFrom((SortableLazyList.SortableEntityProvider)safep, safep, pageSize);
```

I use a temporal workaround in my `PageProvider` with an initialSorting variable set (same as set in the grid/table) and as long as I receive a null or empty sortPropertyId for filtering in the findEntities method I use the initialSorting, but after the first time the sortPropertyId had a value in the findEntities method the PageProvider disables the initial sorting property

If I am not missing something how can I start by and try to fix this in viritin?

**Comment by mstahv** [comment]
Yep, I think I noticed this same once as well. The previous sorting property is not passed to the backend, but it definitely should. Feel free to try to tackle this!

**Comment by mstahv** [comment]
I found some time to investigate this and MTable at least was pretty easy to tackle. Will look into MGrid for a moment now...

**Comment by hofmanndavid** [comment]
Hi Matti, 

Is this fixed in version 53? Because I still have the same issue.

Thanks!

**Comment by mstahv** [comment]
Yes, *should* be ok. If it still don't work, I hope you can share a test case to repeat the issue.
