### ISSUE TITLE
Filterable MGrid with generated properties

### ISSUE THREAD

**Issue by d-bucur** [viritin/viritin#189]
There is no easy way now to have an **MGrid** that is both filterable and with generated properties. **MGrid** is backed by a **GeneratedPropertyListContainer** after calling the generator methods _withGeneratedColumn()_.

**MTable** instead uses **FilterableListContainer** which implements _Filterable_, but there is no easy way to combine these two.

A fast workaround I used in my project was subclassing **GeneratedPropertyListContainer** and copying the _Filterable_ implementation from **FilterableListContainer** and then subclassing **MGrid** to use this new container, but this is hardly very modular. Using decorator pattern would be much better.

**Comment by dve** [comment]
Why not let `GeneratedPropertyListContainer` extend `FilterableListContainer`?

**Comment by mstahv** [comment]
@sird0d0 , do you have an example use case of what you are trying to achieve? I'm trying to figure out if using FilterableListContainer in MGrid makes sense. See related discussion in #206
