### ISSUE TITLE
Simplification of MGrid

### ISSUE THREAD

**Issue by mandjeo** [viritin/viritin#192]
Hi,

I am new to the Grid component, I was using the Table all the time.
So I see it has really a lot of possibilities, however, I would expect the viritin version to be doing more on its own. 
As far as I can see, one needs to create everything from Header to Filter manually?

Is it planned to improve it so that we can have .withColumnHeaders, .withDefaultFilterRow... ?

Thanks!

**Comment by mstahv** [comment]
Hi, would you create individual issues for each enhancement ideas? That would make it easier to track the process and also lower the boundary to start working on them. Thanks in advance!

**Comment by mstahv** [comment]
Closing this. There is a separate issue for defaultFilterRow and withColumnHeaders already exists.
