### ISSUE TITLE
MGrid row-based editor refresh after commit

### ISSUE THREAD

**Issue by yesazo** [viritin/viritin#193]
I have a MGrid initialized with a list of entities. After I save simple text changes using the build-in row-based editor, still the old value appears. If I open the editor with a double-click again, I can edit the new value, but after a commit I can only see the old value. I tried to call an explicit refreshRow from the CommintHandler but it does not help (refreshRows throws an exception). I have also non-ediable columns in the grid and one of them is hidden. Is it a bug or is there a way to refresh the content of a row after a row-based editor commit?

**Comment by mstahv** [comment]
Last time I checked the row based editor works (if you use it in conjunction with refreshRow). What kind of objects you can in your Grid? Do they have equals & hashCode methods written properly?

**Comment by yesazo** [comment]
Thank you for answer. Yes, it was the hashCode/equals method which was implement as required by an entity class (using all the fields). This means after the object has changed (that is why it should be refreshed in the grid), it does not match using hashCode/equals. I made a workaround with a transient flag to be able to use only the ID field in the hashCode and equals methods in this case.
