### ISSUE TITLE
SubSetSelector requirements

### ISSUE THREAD

**Issue by viydaag** [viritin/viritin#199]
You should write that setValue(...) is required to be called for SubSetSelector to be functional.
It throws a NullPointerException if not called when selecting an option.

Also, if the setValue is called with an ArrayList parameter (ex: setValue(new ArrayList<T>());), each time a selection changes, the option is added twice in the MTable. Resolved by setting a HasSet instead.

**Comment by mstahv** [comment]
So far I think I have only used it with Sets, but supporting Lists shouldn't be too hard either.

Also true that null values could be supported like in MultiSelectTable.

I'll try to find time to fix these soon. If you want to help, but don't want to touch the actual field implementation, you could post usage examples, either as pull requests or just as comments here. That would be great help!
