### ISSUE TITLE
Add ability to use container filtering on MGrid

### ISSUE THREAD

**Issue by nilacqua** [viritin/viritin#206]
MTable has FilterableTable extension. However MGrid goes straight to the ListContainer, which doesn't implement Filterable. Please add Filterable to ListContainer or create a FilterableGrid.

**Comment by dve** [comment]
As a workaround you can use `setContainerDatasource` with a `FilterableListContainer` - as long as you don't use generated columns.

**Comment by rubberony** [comment]
A lot of chatter about Grid nested/generated properties.  I did this in my project, it seems to allow sorting of _nested_ properties with minimal change.  I think i probably cheated but...

```
public class CustomFilterableListContainer<T> extends FilterableListContainer<T> {

	public CustomFilterableListContainer(Class<T> type) {
		super(type);
	}
	public CustomFilterableListContainer(Collection<T> backingList) {
		super(backingList);
	}

	@Override
	public Collection<?> getSortableContainerPropertyIds() {
		//This appears to fix the issue of nested properties not being sortable;
		//return super.getSortableContainerPropertyIds();
		return super.getContainerPropertyIds();
	}
}
```

**Comment by mstahv** [comment]
Hello everybody, I finally had a change to look into this with be more time.

I took the PR by @brenzel, merged it with current changes in master, added some tests and enhanced it with the suggestion by @dve to start using FilterableListContainer also in the GeneratedPropertyListContainer. But I didn't yet dare to push it to master, you can see that branch here:

https://github.com/viritin/viritin/tree/feature/filterable-list-container-in-mgrid

The good thing is I did some testing for it and couldn't right away find anything that would be broken. But I still couldn't find any place where it would be superior to doing the filtering in own application code. I added two examples to master how to do filtering with MGrid, both with [in-memory list](https://github.com/viritin/viritin/commit/422d19d6b33e579282d967424b1ce1bdc411183e) and with [lazy loading](https://github.com/viritin/viritin/commit/09450c32c9e38ac9429dbd27f59c19c7edc65da6).

Would you share some examples or general use cases where using the Container.Filterable API would be better than core Java features? I might be also missing some other relevant related to the topic.

Thanks in advance!

**Comment by mstahv** [comment]
For a reference for discussion, here is the example I used for using Filterable API in the feature branch:
https://github.com/viritin/viritin/commit/422d19d6b33e579282d967424b1ce1bdc411183e

It contains one obsolete call to cancelEditor, but still I don't find it any simpler than the "plain java" version in current master branch:
https://github.com/viritin/viritin/commit/422d19d6b33e579282d967424b1ce1bdc411183e

**Comment by mstahv** [comment]
Sorry, wrong first change in previous post, fixed to point to the right one.

**Comment by PhineasClick** [comment]
Is this still under consideration? I'm just came accross this thread when i was trying to apply a Filterbar to an MGrid. So a filterable MGrid which also support generated properties would come very handy. If this is no longer under consideration is will need to go with the stream filtering.

**Comment by mstahv** [comment]
FilterBar?

**Comment by PhineasClick** [comment]
A Headerbar that hosts fields to filter the Grid Columns.

**Comment by mstahv** [comment]
OK, so no existing tool that makes it for you automatically? I think you are better of by making the FilterBar with the "plain Java" way I showed above. Simpler and more forward compatible with upcoming Vaadin versions or with other UI libraries.

I guess I'll close this issue now, if somebody comes up with really good reason to improve Container.Filterable based solutions, I'm all ears.
