### ISSUE TITLE
MBeanFieldGroup updated value access after 1.55 unbuffered change

### ISSUE THREAD

**Issue by gokhanoner** [viritin/viritin#222]
How can I access the modified entitiy ? Now commit returns exception, and when I look to the entity in my ItemDataSource, its still old entity after change..

**Comment by viydaag** [comment]
You should not have to commit any change to the entity since MBeanFieldGroup is in "not buffered" mode. In other words, any change made in the UI are reflect to the bean (if your field name matches with the bean or you have overridden the property name). If you have a database or other storage system, an additional commit is required but outside the MBeanFieldGroup.

**Comment by gokhanoner** [comment]
I've created fileds like `filterBinder.buildAndBind("Start Date", "msgdateMin", DateField.class)` and then i'm calling `filterGroup.getItemDataSource().getBean()` but i get the old bean, it doesn't reflect the changes I made on the fields. And yes, Field names are matched. My form work with 1.54, where I call commit but not with 1.55.

**Comment by gokhanoner** [comment]
Do I need to call `withEagerValidation()` after creating MBeanFieldGroup  or anything else ?

**Comment by mstahv** [comment]
Like @viydaag  said, most of the stuff in Viritin is designed without buffering in mind. Could you create a reduced example what worked before? That would help to figure out the real problem. Let's find out an alternative way to cope with your use case or make it work again.

**Comment by mstahv** [comment]
I changed the throwing into logging in https://github.com/viritin/viritin/commit/de1ac58694453cbcf4c0e293d2c89cd691ed704e , so you should be able to use the next version again with the code that worked before. But I'd still be eager to see the use case to understand this better (and not to break things in the future :-) ).

**Comment by gokhanoner** [comment]
Please see https://github.com/gokhanoner/viritin-demo

**Comment by gokhanoner** [comment]
Any update on this one ?

**Comment by mstahv** [comment]
Hi, I haven't yet found time to look into your example app, but released a version that don't throw exception, but just logs a warning.

**Comment by mstahv** [comment]
Thanks for the example anyway, I'll try to get some time to look into it, just super busy lately with conferences and new releases.

**Comment by mstahv** [comment]
I looked at the demo project you sent, but I didn't yet get it why you'd need to to use buffering there.

**Comment by gokhanoner** [comment]
Matti, im not especially trying to ise buffering mode. I just try to get the updated value after i change the value, which I cannot

**Comment by mstahv** [comment]
Ah, ok. Just call this before you create and bind your fields:

     filterGroup.setBuffered(false);

**Comment by mstahv** [comment]
The constructor should probably also set the non buffered mode on by default...

**Comment by gokhanoner** [comment]
Yep, this works. My assumption was it's already not buffered, because in the documentation on commit method, it says 

> /**
     * Viritin does not support buffering. Calling this function with buffered=true
     * will cause an UnsupportedOperationException.
     * @see <a href="https://github.com/viritin/viritin/issues/186">Issue 186</a>
     * @deprecated
     */

**Comment by mstahv** [comment]
I fixed the documentation in https://github.com/viritin/viritin/commit/adfe0fd0eca2b7278a03fcb5b03e8f6cbc826b97
