### ISSUE TITLE
MGrid not refreshing

### ISSUE THREAD

**Issue by slibert** [viritin/viritin#226]
Hi,

Can't achieve any item refresh after edition.

Code is quite simple, I create a custom MGrid with 
`
list = new SortableLazyList<T>((SortableEntityProvider<T>)service);
flc = new FilterableListContainer<T>(list);
setContainerDataSource(flc);
`

Later in the code, one row has changed, I'd like to refresh it so it displays brand new values :
`
grid.refreshRow(refreshedItem);
grid.refreshVisibleRows();
grid.refreshRows();
`
... no one has any effect. Any clue ?

**Comment by mstahv** [comment]
Sounds quite weird, could post a full usage example where I could reproduce the issue.

**Comment by slibert** [comment]
Hello Matti,

Thanks for giving time to this case.

That's quite a difficult work to make a standalone example, as we are working with a custom service entity relying on JPA code. But if it's necessary, i'll try to do so.

Meanwhile I made some more searches and I think my problem is related to investigations you made with Edouardo Vacchi. For the references :
https://vaadin.com/forum#!/thread/9319379
https://dev.vaadin.com/ticket/16765
https://github.com/viritin/viritin/issues/57#issuecomment-75030246

What was the final solution/workaround to this problem ?

Regards

**Comment by bhorvath** [comment]
I'm experiencing a similar issue with MGrid and LazyList if I edit an entity outside of the grid (eg. directly in the database) and then try to refresh the changes.

Here is the code snippet:
```
    @Override
    public void enter(ViewChangeEvent event) {
	final MGrid<TblAddress> grid = new MGrid<>(this::getEntities, this::getEntityCount);
	this.addComponent(grid);

	final Button refreshButton = new Button("Refresh");
	this.addComponent(refreshButton);
	refreshButton.addClickListener(e -> {
	    grid.refreshRows();
	});

	final Button streetAddressButton = new Button("Street Address");
	this.addComponent(streetAddressButton);
	streetAddressButton.addClickListener(e -> {
	    logger.debug("streetAddressButton: "
		    + Optional.of(grid).map(MGrid::getSelectedRow).map(TblAddress::getStreetAddress).orElse(""));
	});

    }

    public List<TblAddress> getEntities(final int startIndex) {
	EntityManagerProvider.getEntityManager().getEntityManagerFactory().getCache().evictAll();
	final TblAddress address = DaoFactory.getAddressDao().findById(200000);
	logger.debug("getEntities: " + address.getStreetAddress());

	return Collections.singletonList(address);
    }

    public int getEntityCount() {
	return 1;
    };
```

If I update tblAddress.StreetAddress in the database and then click on refreshButton, the new value is logged in getEntities, but the old value is logged when clicking streetAddressButton. Strangely the new value is initially displayed in the grid, however if I select and unselect the row then it reverts back to the old value.

**Comment by mstahv** [comment]
IIRC it was fixed already. My wild guess would be that your JPA entities have some kind of invalid equals/hashCode implementations. Could you share those for evaluation?

In Vaadin 7.7.4 there even seems to be a new public method to help refreshing a specific row directly. You could also try using that.

Let me know if you got this resolved or if I should try to help you still.

**Comment by bhorvath** [comment]
Yes, you are correct. The entities were being compared by their primary key. They are now being compared by business keys and that has fixed the issue.
