### ISSUE TITLE
"Hot swapping" FilterablePagingProvider and FilterableCountProvider of a LazyComboBox

### ISSUE THREAD

**Issue by lorenzobenvenuti** [viritin/viritin#230]
Hi Matti,

is there any way to "hot swap" FilterablePagingProvider and FilterableCountProvider of a LazyComboBox? In our application we have some combos whose items change depending on the value of other Fields. As a temporary solution I implemented a CustomField that changes the composition root of a Panel using a new instance of LazyComboBox every time we need to change the content, but this doesn't seem the best solution.

Thank you,

lorenzo

**Comment by mstahv** [comment]
I guess LazyComboBox should have similar (lazy)loadFrom methods as there is in MTable (and MGrid)? I'll see if that would be easy to add.

**Comment by lorenzobenvenuti** [comment]
Thank you Matti! I submitted a pull request (I tried a quick and dirty implementation when I read your comment) but I see you already did it!
