### ISSUE TITLE
the method  "configureMaddonDefaults" is forcing the field to required when this is readOnl

### ISSUE THREAD

**Issue by fphilip** [viritin/viritin#232]
Hello

t is correct? or may be ignoring validation and required if readonly is true

` public void configureMaddonDefaults() {
        for (Object property : getBoundPropertyIds()) {
            final Field<?> field = getField(property);

            try {

                // Make @NotNull annotated fields "required"
                try {
                    java.lang.reflect.Field declaredField = findDeclaredField(
                        property, nonHiddenBeanType);
                    final NotNull notNullAnnotation = declaredField.
                        getAnnotation(
                            NotNull.class);
                    if (notNullAnnotation != null && !field.isReadOnly()) { 
`

**Comment by mstahv** [comment]
Sounds like a good change to me: if you don't want to allow your users to edit a field, it probably makes no sense to mark it required in the UI either.

Thanks, I can push this change in right away!
