### ISSUE TITLE
Adding .withGeneratedColumn to MGrid

### ISSUE THREAD

**Issue by mandjeo** [viritin/viritin#236]
Compared to MTable, MGrid doesn't include .withGeneratedColumn method where an extra generated column could easily be added.

**Comment by mstahv** [comment]
It does actually, which version are you using?

The only thing it doesn't support is components, but that limitation is in core and cannot change that in Viritin, as the project only aims for server side enhancements. If you want to use components in Grid, see ComponentRendered add-on in the directory. Its ComponentGrid classes API is inspired by Viritin so it should be really easy to use ;-)
