### ISSUE TITLE
LazyList does not support remove

### ISSUE THREAD

**Issue by viydaag** [viritin/viritin#248]
Is there a reason why LazyList throws an UnsupportedOperationException when getContainerDataSource().removeItem(bean) is called on the MGrid?

**Comment by mstahv** [comment]
Is there something we could do there? I'd say in most cases no.

In what kind of case you are calling getContainerDataSource().removeItem(bean) ? I think you should just go directly to your "backend" (EJB, CDI bean, Spring Service, Repository), delete the entity there and then call MGrid.refreshRows().

**Comment by viydaag** [comment]
Thank you for the suggestion. I'll try that later. 
I am migrating my old grids to mgrids and my way to remove a row was to delete the bean from the container. Now I see that mgrid does not support property change listeners.
