### ISSUE TITLE
NPE in SortableLazyList when no sort properties are given

### ISSUE THREAD

**Issue by mcollovati** [viritin/viritin#249]
SortableLazyList.findEntities throws a NPE when initialized without sort properties.
NPE comes from getting first element of sort properties array that could be null (getSortProperty()[0]) 

```java
    protected List<T> findEntities(int i) {
        if(multiSortablePageProvider != null) {
            return multiSortablePageProvider.findEntities(i, getSortAscending(), getSortProperty());
        }
        return sortablePageProvider.findEntities(i, isSortAscending(), getSortProperty()[0]);
    }
```

To reproduce lauch UI test `AspectAttributeTest.testLanguageByBrowser`; it will show error in browser window (and STDOUT of course).

**Comment by mstahv** [comment]
Thanks, fixed in [b26750e]
