### ISSUE TITLE
LazyComboBox filter lowercase

### ISSUE THREAD

**Issue by SlinToWin** [viritin/viritin#251]
I try to implement a "new" mechanism where PagingProvider generates a new Item with the given Filter.

Problem is, that filter is always lowercase.
There is no chance to filter case sensitive or creating a new item with the original user input.
Is there a way to get the original user input from LazyComboBox?

**Comment by mstahv** [comment]
Good enhancement idea. I actually needed this once in the past as well. IIRC ComboBox rudely calls toLowerCase as a very first step in changeVariables method. Maybe overriding that and stealing the original filter string from the variable map to some temporary location would do it? I'd not like to completely override the cores implementation.

**Comment by mstahv** [comment]
But that hack described above could indeed be added to LazyComboBox and and the last know *original* filter string could be exposed via API.

**Comment by mstahv** [comment]
It was actually pretty easy to do. If the component wasn't already in pretty heavy use, I would have made the raw mode the default.

**Comment by SlinToWin** [comment]
Hey Matti, thanks for your work :) Thanks a lot!
