### ISSUE TITLE
MTable : add listeners fluently?

### ISSUE THREAD

**Issue by canthony** [viritin/viritin#256]
Is there any practical or technical reason that MTable doesn't have any fluent withValueChangeListener/withRowClickListener/withSortListener methods?

Happy to implement some time, just checking to see if there was any reason they weren't present.

**Comment by mstahv** [comment]
Nope, probably just laziness or then different focus in mind when doing MTable stuff. I think they would make a lot of sense. Thanks in advance!

**Comment by canthony** [comment]
withValueChangeListener - Hmmmmm. Philosophical question:
Should it be with**M**ValueChangeListener(MValueChangeListener listener) to differentiate from ValueListener (showing the type in the method name) - or should it be withValueChangeListener(MValueChangeListener listener).

For me, using the M in the method name is a bit of clutter - MValueListener *is* a value listener, just a typed one; however, it might be seen as going against the method naming patterb

**Comment by mstahv** [comment]
I'd also leave the M away. I think nobody needs the worse version of the listener, no need to support it with fluent API.

**Comment by canthony** [comment]
:thumbsup:
