### ISSUE TITLE
TypedSelect<SomeBean>(Combobox.class) doesn’t show the selected value, but getValue() is allright.

### ISSUE THREAD

**Issue by vonloxley** [viritin/viritin#267]
Please see the attached test case.
[TypedSelectWithBean.java.txt](https://github.com/viritin/viritin/files/648180/TypedSelectWithBean.java.txt)

**Comment by lorenzobenvenuti** [comment]
I didn't try to run your code, but from the description is seems to be similar to this issue: https://github.com/vaadin/framework/issues/7902

**Comment by vonloxley** [comment]
Great! Thanks a lot.

**Comment by jpook** [comment]
Hi, thx for the fix. But what does 'ensure list container is properly set to backing select before setting value' exactly mean ? Do I have to do anything different here for data binding than to other fields ?

**Comment by mstahv** [comment]
With selects you'll need to set the available options, e.g. using *setOptions(List<T>)*, before setting the value of the field, nothing more.

**Comment by jpook** [comment]
Thanks for the fast reply ! But sorry for asking again: I use TypedSelect in a form and I set the options as mentioned. All other fields are bound to the according fields by naming. Do I actively have to select the value for TypedSelect or does data binding by name also work here ?

**Comment by mstahv** [comment]
Binding should work just fine. Ensure you have proper equals/hashCode implementation in your objects, if different instances can mean the same logical option.

**Comment by jpook** [comment]
Thanks ! I'll have a try on it :)
