### ISSUE TITLE
Boolean allowAddingNewItems of Method setNewItemsAllowed of SubSetSelector is never used 

### ISSUE THREAD

**Issue by jissart1** [viritin/viritin#268]
Hello,
I wanted to use the setNewItemsAllowed method of  [SubSetSelector.class](https://github.com/viritin/viritin/blob/fdf93ffef94451a6744c243b3ae43c402f2ab9a2/src/main/java/org/vaadin/viritin/fields/SubSetSelector.java), but I can see in the code than the parameter allowAddingNewItems is never used in the method.

```
 public void setNewItemsAllowed(boolean allowAddingNewItems) {
         cb.getSelect().setNewItemsAllowed(true);
         cb.getSelect().setNewItemHandler(new AbstractSelect.NewItemHandler() {
             @Override
             public void addNewItem(String s) {
                 addEntity(s);
             }
         });
 }
```

**Comment by mstahv** [comment]
Thanks, should be fixed now, but had not time to build test for it. Can you verify it works (with a local snapshot build or with next version which I plan to cut soonish).

**Comment by jissart1** [comment]
Hi,
I've tested with the version 1.61 of Viritin. 
It's OK for me.

Thank you.

Have an happy new year !
