### ISSUE TITLE
PropertyComparator only compares first property in array

### ISSUE THREAD

**Issue by larskn** [viritin/viritin#269]
This was introduced in 9da4a9c31aabb8ea74e3739bff5c3a22930ae9f8 when the `if (compare != 0)` check was removed.

**Comment by connor-bracewell** [comment]
Whoops. I was responsible for that change, not sure that got overlooked. Fix should be as simple as adding the check back in; I'll make a fix and submit a pull request later today unless someone else beats me to it.
I guess there should also be some tests for that, I'll put it on my to-do list as well.
