### ISSUE TITLE
MGrid and refreshRows()

### ISSUE THREAD

**Issue by SlinToWin** [viritin/viritin#278]
There seems to be an issue with refreshRows implementation of MGrid.

Test Case:

 | POINTS |

 ----------

 |       17    |

Displaying Data: "17"

Now i update the models in my database to e.g. 15
After that i call grid.refreshRows();

The Grid is refreshed and it displays 15.
Now i select the cell and after that another one and the value changes back to 17.

Seems there is a caching issue. I've checked the XHR Requests from Vaadin and the return the wrong 17. 
When i reload the whole page the data is displayed correctly.

Any workarounds for that?
I'm a little bit confused because it seems like some kind of internal caching.

Thanks for your help :)

**Comment by SlinToWin** [comment]
I've checked the Container and the items have the correct values. It seems only that the Frontend cache is not correctly resetet (?)

**Comment by SlinToWin** [comment]
Argh, found the Answer.

```
                 for (Extension extension : getExtensions()) {
                    if (extension instanceof RpcDataProviderExtension) {
                        RpcDataProviderExtension rpc = (RpcDataProviderExtension) extension;
                        rpc.getKeyMapper().removeAll();
                        break;
                    }
                }
```

Removing all Items from Keymapper did it for me.
This also resolves a similar bug with Grid Buffered Editor

**Comment by AdrienC** [comment]
Thanks!
This should be in MGrid.
