### ISSUE TITLE
Viritin jar contains rebel.xml

### ISSUE THREAD

**Issue by florianschmitt** [viritin/viritin#293]
Hey, version 2.0.alpha1 contains a rebel.xml which probably shouldn't be there!

`[2017-03-01 15:23:30] Invalid rebel.xml: Invalid 'dir' defined in class path of rebel.xml (jar:file:/C:/guh/caches/modules-2/files-2.1/org.vaadin/viritin/2.0.alpha1/a0d6b6885097b2144c3d5bf0c08244d6459849be/viritin-2.0.alpha1.jar!/rebel.xml): Directory '/Users/mattitahvonenitmill/git/viritin/target/classes' does not exist`

Cheers, 
Florian

**Comment by mvysny** [comment]
(y)

**Comment by mstahv** [comment]
Oops, had accidentally committed that at some point. Now removed.
