### ISSUE TITLE
missing setFieldType in LazyComboBox

### ISSUE THREAD

**Issue by darjag** [viritin/viritin#295]
I think that missing a set field type in initList(...) method. Without that I have two times run findEntities()
1) from getType() in TypedSelect class, becouse get first item id from containter when filedType is null
2) when combobox is painting

**Comment by mstahv** [comment]
I suggest to use the constructor with the actual type class as parameter + lazyLoadFrom methods. Do you get extra findEntities then as well?

**Comment by darjag** [comment]
In my case I extend LazyComboBox class and in my constructor call initList method. I check it with constructor from LazyComboBox class and is OK. At the moment I don't understand why it's work fine. Apparently I missed something. Issue may be closed.
Thank You for your good job for viritin and vaadin :)
