### ISSUE TITLE
IntegerField internal value not set using Binder

### ISSUE THREAD

**Issue by markathomas** [viritin/viritin#298]
The internal value of IntegerField is only set when the ValueChangeListener on the TextField is invoked; however, this only occurs after attach() has been called which calls getContent() of CustomField thus if you implement logic in the constructor of a widget that uses IntegerField and Binder before attach() has been called the internal value of IntegerField remains null.

**Comment by mstahv** [comment]
Hi Mark!

Blindly I'd move the hooking of the value change listener to the constructor of the AbstractNumberField. That might do the trick? Could you write a small example/test code for this?

**Comment by markathomas** [comment]
Sure, I'll give it a try and generate a test.

Regards,

Mark Thomas
spatialguru.net@gmail.com
205.529.9013

"Commit to the Lord whatever you do,
    and your plans will succeed." - Proverbs 16:3

**Comment by markathomas** [comment]
Here's an example project showing the problem.  Note that if you uncomment line 29 in Widget.java an exception is thrown.
[example.zip](https://github.com/viritin/viritin/files/979157/example.zip)

**Comment by markathomas** [comment]
Also, IntegerField does not accept a ValueChangeListener in any constructor so i cannot test that suggestion for you.  As an aside, I noticed a bug in Vaadin core binding that if any ValueChangeListener is added before the binding occurs the VCL is not fired on call to Binder.setBean(model).

**Comment by mstahv** [comment]
There seems to be double value change events as well, I'll fix those too...

**Comment by mstahv** [comment]
Can you share a link to the core issue (I assume you created one)?

**Comment by markathomas** [comment]
i didn't ;0(  jsut worked around it then forgot to.  should i create one?

Regards,

Mark Thomas
spatialguru.net@gmail.com
205.529.9013

"Commit to the Lord whatever you do,
    and your plans will succeed." - Proverbs 16:3

**Comment by mstahv** [comment]
Please do, I'll then tease our R&D team to fix it soon ;-)

**Comment by markathomas** [comment]
Looks like this is no longer a problem in latest Vaadin version.  Seems to
only be an issue with IntegerField and related components.

Regards,

Mark Thomas
spatialguru.net@gmail.com
205.529.9013

"Commit to the Lord whatever you do,
    and your plans will succeed." - Proverbs 16:3

**Comment by mstahv** [comment]
OK, perfect. I'll cut a new release of Viritin soon.
