### ISSUE TITLE
Startup error after upgrading to Vaadin 8 and Viritin 2.0.beta1

### ISSUE THREAD

**Issue by natami** [viritin/viritin#301]
I started getting the following client side error after upgrading to latest Viritin 2.0.beta1:

Widgetset 'com.vaadin.DefaultWidgetSet' does not contain implementation for org.vaadin.viritin.v7.fields.MPasswordField/MCheckBox. Check the connector...

I've tried configuring the vaadin-maven-plugin without success.

**Comment by andreika63** [comment]
Hi,
try to do this:
at UI class add annotation 

> @Widgetset("com.vaadin.v7.Vaadin7WidgetSet")

and at pom.xml add

> 		<dependency>
> 			<groupId>com.vaadin</groupId>
> 			<artifactId>vaadin-compatibility-client-compiled</artifactId>
> 			<version>${vaadin.version}</version>
> 		</dependency>

${vaadin.version} - vaadin version you are using

**Comment by natami** [comment]
Thx, this did the trick :)

**Comment by mstahv** [comment]
Yep, V7 compatibility client side stuff is need, if using compatibility components.
