### ISSUE TITLE
MTable. Change type of property

### ISSUE THREAD

**Issue by Nixic** [viritin/viritin#306]
Hello!
Is it possible to show in column with Boolean type, String message, like Yes or No?
Maybe I can change type of property or another path is exist to do this?

I had try to use ListContainer, but method addContainerProperty() is Unsupported yet.

Thanks!

**Comment by andreika63** [comment]
Hi Nixic!
In this case I'm using enums:

> public enum YESNO{
>         N("No"),
>         Y("Yes");
>         private final String title;
>         Dtype(String title) {
>             this.title = title;
>         }
>         @Override
>         public String toString() {
>             return title;
>         }
>     }

**Comment by Nixic** [comment]
Thank for you answer!
I had solved my problem by adding new field(s) to my Entity classes with types what I needed and with annotation @Transient.
Business Logic, I added in getters

**Comment by mstahv** [comment]
You shouldn't use ListContainer directly, but override the presentation via MTable/MGrid, using withGeneratedColumn method in MTable or using standard mechanism with the new V8 Grid.
