### ISSUE TITLE
IntegerField throws NullPointerException

### ISSUE THREAD

**Issue by viydaag** [viritin/viritin#309]
IntegerField throws NullPointerException when setting callsign setEntity(null) on the AbstractForm.

I think the field should set the "empty value" instead of null when setting the field is cleared. (see doSetValue)

**Comment by mstahv** [comment]
Hi, do you have an example code that can reproduce the issue? That would speed up to build a fix for this.

**Comment by viydaag** [comment]
Here is a simple component code to reproduc the situation. Just add this to your ui and compile.
When the form is displayed, enter a number in My Integer field (the cancel button will be enabled) and click on Cancel (it will call setEntity(null)). An exception is thrown because AbstractTextField cannot have a null value.

`import org.vaadin.viritin.fields.IntegerField;
import org.vaadin.viritin.form.AbstractForm;
import org.vaadin.viritin.form.AbstractForm.ResetHandler;

import com.vaadin.ui.Component;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.VerticalLayout;

public class PojoForm extends VerticalLayout {

    private static final long serialVersionUID = -3372312513086236945L;

    public PojoForm() {
        AbstractForm<Pojo> form = new AbstractForm<Pojo>(Pojo.class) {
            
            private static final long serialVersionUID = 1251886098275380006L;
            IntegerField myInteger = new IntegerField("My Integer");

            @Override
            protected Component createContent() {
                FormLayout layout = new FormLayout(myInteger, getToolbar());
                return layout;
            }
        };
        
        form.setResetHandler(new ResetHandler<Pojo>() {
            @Override
            public void onReset(Pojo entity) {
                form.setEntity(null);
            }
        });

        form.setEntity(new Pojo());
        addComponent(form);
    }

    
    public class Pojo {

        private Integer myInteger;

        public Pojo() {
            myInteger = null;
        }

        public Integer getMyInteger() {
            return myInteger;
        }

        public void setMyInteger(Integer myInteger) {
            this.myInteger = myInteger;
        }
    }

}`

**Comment by mstahv** [comment]
Thanks! I initially tried to reproduce the issue with unit test, but couldn't succeed with that. Now fixed.
