### ISSUE TITLE
Remove deprecated methods

### ISSUE THREAD

**Issue by dve** [viritin/viritin#330]
Since there is not a 2.0 release yet, should we not remove deprecated methods to clean up?

**Comment by dve** [comment]
Ok, to late: 1e263ab 

@mstahv do we have a plan when to remove deprecated methods?

**Comment by mstahv** [comment]
I wanted to get the first "stable" out, but we have plenty of numbers. Which do you think should we get rid most urgently?

**Comment by dve** [comment]
I thought about the withWidthUndefined ones

**Comment by mstahv** [comment]
I think we could get rid of them in a minor version as well, I guess nobody will blame us about that.
