### ISSUE TITLE
Split up v7 stuff to module

### ISSUE THREAD

**Issue by dve** [viritin/viritin#331]
We should move the vaadin-7 stuff to a `viritin-compatibility` maven module like in vaadin core or touchkit. Pure vaadin-8 projects don't need to pull in the 'vaadin-compatibility-*' jars anymore

**Comment by dve** [comment]
@mstahv what do you think about this? I can start to prepare a pull request for this

**Comment by mstahv** [comment]
That would be awesome!

**Comment by dve** [comment]
I've pushed a new branch. Could you look at the osgi manifest stuff, since I have no knowledge about it.

**Comment by mstahv** [comment]
Took that to master. Had to rename v7 stuff to a different package name to cope with osgi requirements (and java9 modules as well). Will build first releases and publish the combatibility package to directory as well.

I guess we could move the compatibilty stuff also to a separate git repo at some point. I don't think there will be too many changes for that part anymore.
