### ISSUE TITLE
Allow read-only fields in ElementCollections

### ISSUE THREAD

**Issue by endertunc** [viritin/viritin#332]
Why ElementCollections does not let you have fields with read-only? 

I believe that it is absolutely valid case for business applications to have some fields to be read-only in some circumstances. For instance, admin and non-admin users will have same view with some differences.

Not sure if it is related with Vaadin or Viritin but one thing I notice while I trying to make some fields to be read-only is that we can't use label in the ElementCollections. It basically doesn't show up on the UI. Why is that? Is it intentional or some sort of bug?

Thanks.

**Comment by dve** [comment]
Can you give an example? I guess its because if a field is set readOnly you can not set a value anymore.

There is a LabelField once created for something like an id maybe that will help you?

**Comment by endertunc** [comment]
@dve Thanks that worked! I did tests with Vaadin's Label and seems like it doesn't work well with ElementCollections as I pointed in my question. I don't know how did I miss the LabelField even though I use auto-complete.

**Comment by dve** [comment]
@endertunc Vaadin's Label is not a field - that the problem with it

**Comment by endertunc** [comment]
@dve that must be it. The issue can be closed.

**Comment by dve** [comment]
Since the javadoc changes are merged into the master, this can be closed.
