### ISSUE TITLE
Feature Request: DownloadButton that can fail

### ISSUE THREAD

**Issue by knoobie** [viritin/viritin#356]
Hey,

we have the following requirements: 

A DownloadButton can fail. (example if we can not generate the file the user wants to download, we should show an error message) 

Do you see a way to do that with the current implementation using the ContentWriter Constructor? Returning an empty writer or closing the writer did not to the trick (empty file was served)

Thanks!

**Comment by mstahv** [comment]
Do you think the change I did would serve your needs? If you think it is ok, I'll cut a release soon.

**Comment by knoobie** [comment]
Working wonderful! Thank you :+1: 

Now I can add additional error handling with the given ComponentError. 

![grafik](https://user-images.githubusercontent.com/3968629/42313155-51d761b4-8042-11e8-8ed7-74242a5b6162.png)

Best wishes!
