### ISSUE TITLE
Sarjan lisääminen ja jonojen siirto helpoksi

### ISSUE THREAD

**Issue by rydekivinen** [viritin/viritin#378]
Moro

Liittymään mahdollisuus lisätä sarja, jota Irma-filusta ei tule (ei osallistujia).

Sarjojen määrittelyyn mahdollisuus napilla (tai napilla + valinnalla) lisätä x minuuttia ensimmäiseen lähtöaikaan ja samalla myös vaihtaa lähtöväli tarvittaessa. Sarjamäärittelyn lehdellä myös näkyviin ensimmäinen lähtöaika ja lähtöväli. Ei tarvitse yrittää muistaa moisia... 

Sitten oltaisiin aika lähellä "meleko hyvää"...  ;)

T. Ryde

**Comment by mstahv** [comment]
Moved to different repository: https://github.com/mstahv/start-time-selector/issues/15
