### ISSUE TITLE
BrowserCookie NPE when reading cookie

### ISSUE THREAD

**Issue by UnderConstruction** [viritin/viritin#53]
I have an application that needs @Push and cookies, so I'm using Viritin to handle the cookies.

I am getting a NullPointerException when the cookies are read using BrowserCookie.

I am able to reproduce the problem in the attached test program (86 lines).

It does not matter if @Push is enabled or not -- reading a cookie that has been set always causes an NPE.

The code is available in the [Vaadin forum.](https://vaadin.com/forum#!/thread/9199732)

To reproduce the problem:
1) Click on the "Read Cookies with Viritin".  The console will show:
> readViritin::buttonClick()
>   callback for alpha, value = null
>   callback for bravo, value = null

This is correct because the cookies for alpha and bravo have not been set yet.

2) Enter data into the Alpha and Bravo fields, such as "test1" and "test2".

3) Click on the "Save Cookies with Viritin".  The console will show:
> saveViritin::buttonClick()

4) Click on the "Read Cookies with Viritin".  The console will show:
> readViritin::buttonClick() 
>   callback for alpha, value = test1
>   [Two NPE stack traces inserted here]
>   callback for bravo, value = test2

The code I'm using to save a cookie is:
```java
BrowserCookie.setCookie(COOKIE_NAME1, alpha_field.getValue());
```

The code I'm using to read the cookie is:
```java
BrowserCookie.detectCookieValue(COOKIE_NAME1,
    new BrowserCookie.Callback() {
        @Override
        public void onValueDetected(String value) {
            System.out.println("  callback for " + COOKIE_NAME1 + ", value = " + value);
        }
    }
);
```

**Comment by petarov** [comment]
@mstahv Sorry to ping you on this, but this change does not seem to be in the `master` branch anymore. Was this intended?

**Comment by mstahv** [comment]
https://github.com/viritin/viritin/blob/master/viritin/src/main/java/org/vaadin/viritin/util/BrowserCookie.java#L79

It looks to me that it is. Are you experiencing some similar issue? Can you share a code snippet to reproduce it?

**Comment by petarov** [comment]
I'm getting a NPE just like the OP, but I now realise my workflow is a bit different. 

1. I set a `BrowserCookie.setCookie` on a `Button.click` event
2. Then I refresh my UI in the browser and try to read that cookie using `BrowserCookie.detectCookieValue`, in the Vaadin `init(VaadinRequest request)` method. 

However, the `value` I get in the callback is `null`.

My question was whether this extra part here should be in the `master` branch. 

```javascript
{%1$s( c.substring(nameEQ.length,c.length)); break;}
```

Unfortunately, after trying that one, I still get `null`,  so in any case my workflow is probably wrong.
