### ISSUE TITLE
Grid is not refreshed on edit

### ISSUE THREAD

**Issue by evacchi** [viritin/viritin#57]
Steps to reproduce:

```java
class Address {
  String city;
  // constructor, get, set
}
final Grid grid2 = new Grid();
grid2.setEditorEnabled(true);
ArrayList<Address> addrs = new ArrayList<>();
addrs.add(new Address("foo"));
grid2.setContainerDataSource(new ListContainer<>(Address.class, addrs));
```

* double click address "foo"
* change "foo" to "bar"

nothing happens in the grid, but the underlying collection has actually changed

Unfortunately I am not sure how to fix this, but I the BeanItemContainer works, so I guess something is missing in Viritin

EDIT: code was instantiating BeanItemContainer instead of ListContainer

**Comment by mstahv** [comment]
So the above works but not with ListContainer? If that is the case, I'd guess Grid depends on property value change listeners. If they can be added without performance penalty, I have no objection to add support for them, should be pretty easy. But if that causes CPU/memory drawbacks we should introduce an extended version.

**Comment by evacchi** [comment]
Well `BeanItem`'s Properties (apparently they are `MethodProperty`) extend `AbstractProperty` which in turn implements `Property.ValueChangeNotifier`, but Grid itself does not seem to add listeners. I really am not sure about what is happening here; otherwise I would have fixed it myself and PR'd (as I usually try to do)

**Comment by evacchi** [comment]
Nope, I have tried to extend `AbstractProperty` and invoke `fireValueChange()` but nothing happens https://github.com/evacchi/viritin/commit/43b543200cfae428e5b916b9ab155be073a103a7

**Comment by evacchi** [comment]
Ok, so here where the problem seems to be originating from:

```java
    public Item getItem(Object itemId) {
        ...
        return new DynaBeanItem<T>((T) itemId);
    }
``` 

which you do for obvious memory-consumption reasons.

However, throughout Vaadin one assumption is often made, that is: `getItemId(id) == getItem(id)`; in other words, if you request an `Item` for a given `itemId` more than once, there is code in Vaadin that assumes that the **same** `Item` instance is returned. This has bitten me already in the past, while working on the BufferedMongoContainer (which is meant to work with a Table). 

The workaround in our case was *acceptable* but not pretty (because it's non-standard): we added the `updateItem(id)` method so that the user may preemptively signal to the container that (s)he wants to initiate an editing process. This makes the id/item pair to "stick"; in other words, the `BeanItem` instance (MongoContainer uses `BeanItem` internally) is kept until you either `commit()` or `discard()`. 

The problem is not occurring in the BeanItemContainer because (obviously) it is not lazy in any way (and that is exactly the reason why it uses more memory)

**Comment by mstahv** [comment]
A optional cache with weak references to the item? This will probably consume some CPU, but memory wise this shouldn't be an issue -> for most it might be a perfect compromise.

For me this has never been a problem, but thats probably due to the fact that I'm not a big fan of inline editing.

**Comment by evacchi** [comment]
so, basically a [WeakHashMap](http://docs.oracle.com/javase/7/docs/api/java/util/WeakHashMap.html) ?

I was thinking about a proxy to `(Filterable)ListContainer` that delegates every call to `Container.Indexed & Container.Filterable & Container.Sortable` to the `FilterableListContainer` except that on `getItem(id)` it looks into the `WeakHashMap`. What do you think?

**Comment by evacchi** [comment]
I have fixed the glitches (had to delegate `Container.ItemSetChangeNotifier` as well) do you think this would be a reasonable fix? I am not sure because we'd have to tell users of Viritin and MongoContainer that *sometimes* (when Grid is used) this wrapper is required. I'm not sure how I feel about this, but I also feel like this is the simplest, most reusable solution.

**Comment by mstahv** [comment]
Hi, couple of comments by just quickly looking the codes via github:

 * The correct fix for this would be in Vaadin itself, it should use equals when comparing items and the all items wrapping a pojo should write a proper equals/hashcode implementation. I wouldn't hold my breath about when this could be included in the core, but if you find some time and motivation, I would be awesome improvement.
 * Shouldn't you should use normal HashMap and WeakReference instances holding reference to actual items? The cache maps should then be cleaned from time to time. Pojo wrapping items refer to the pojo (= key) so I'm afraid the stuff in cache is never collected.
 * If there is a proper solution with only moderate performance drawback, the workaround (returning same cached instance) should be the default behaviour and the optimised version behind a configuration.

**Comment by evacchi** [comment]
> Shouldn't you should use normal HashMap and WeakReference instances holding reference to actual items? The cache maps should then be cleaned from time to time. Pojo wrapping items refer to the pojo (= key) so I'm afraid the stuff in cache is never collected.

I am currently using a `WeakHashMap<Object, SoftReference<Item>>`, which should be basically equivalent to a `HashMap<WeakReference<Object>, SoftReference<Item>>`. But in fact I fear that you are right. The problem is these weak/soft references are collected only when no more strong references exist. If the itemId is also a bean (or a value inside the bean such an `ObjectId` -- MongoContainer) they will never be actually collected. I feel like using that, in this context, these *References would not do much good, beside adding one indirection level. It is probably safer use a timed cache such as the one in Guava; but then again, what if the cache expires while the Item is still in the viewport?

I believe that the safest bet would be a mechanism *inside* the Grid. Such as a very simple `refreshItem(itemId)` to be called on demand when editing is done in a separate view, and automatically by Grid itself when it is inline.

**Comment by mstahv** [comment]
In [595c571] I made a prototype of recycled items. I didn't test it that much and verify things are GC:d properly. Let me know if you find this useful, so I can merge it to master branch.

**Comment by mstahv** [comment]
I didn't want to add property value change listeners as it would consume more memory and cpu, but added a hook to refresh the edited row when editor row is committed. Let me know if this don't work for you.
