### ISSUE TITLE
setMargin(true) and setSpacing(true) by default on all Layouts

### ISSUE THREAD

**Issue by marlonrichert** [viritin/viritin#81]
All Layouts should have margins and spacing turned on by default. Having them turned off makes them significantly harder to theme.

**Comment by mstahv** [comment]
Currently in Viritin (margin/spacing)

 * MVerticalLayout on/on
 * MHorizontalLayout off/on
 * MGridLayout on/on

I have left MHorizontalLayout off as in most cases (not in all) I want horizontal layouts not to have margin. I have quite many apps from where I have derived these defaults.

In general, I think theme building shouldn't affect these defaults at all. IIRC in V6 era it was possible to define margins and spacings with css even if they where off. I might be wrong, but that is at least how it should work. Then you could e.g. define some minimal spacings (with css) even if they are turned off and larger spacings when on.

**Comment by sebgymn** [comment]
@mstahv +1
