### ISSUE TITLE
Read only not working with LazyComboBox

### ISSUE THREAD

**Issue by florianschmitt** [viritin/viritin#82]
Hey, 

it seems read only is not working for subclasses of LazyComboBox (at least). In my implementation I had to add 
```	@Override
	public void setReadOnly(boolean readOnly)
	{
		getSelect().setReadOnly(readOnly);
	}
```
to make it work. Thanks :+1:

**Comment by mstahv** [comment]
Thanks for the heads up, will build a new release later today!

**Comment by florianschmitt** [comment]
cool! thanks for the good work!

**Comment by mstahv** [comment]
Sorry that I haven't yet build the release, working on some additional renewals...

**Comment by florianschmitt** [comment]
No problem! I'm pleased to hear that and I'm looking forward to checking it out
