### ISSUE TITLE
Type mismatch exception for MTextField

### ISSUE THREAD

**Issue by KelibiaPort** [viritin/viritin#85]
Hi 
I have created a MTextField to store double field. So I have added an StringToDoubleConverter. 
But once I add an integer value, I got this exception

org.vaadin.viritin.fields.MTextField: com.vaadin.data.util.MethodProperty$MethodException
...
Caused by: java.lang.IllegalArgumentException: argument type mismatch

Is there any thing wrong I am doing it ??

Thanks for helps

**Comment by mstahv** [comment]
This is regression for my largish refactorings.
