### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by wassimz** [viritin/viritin#88]
I think vaadin is missing a proper integration of a scheduler support like for example quartz...
it will be great if viritin can support a default integration of such feature

**Comment by mstahv** [comment]
Not sure if this is something that belongs to Viritin. Have you tried using e.g. DeltaSpike Scheduler with Vaadin? I think it should work pretty well, but you naturally need to take care of wrapping UI modifications with UI.access(Runnable).

https://deltaspike.apache.org/documentation/scheduler.html

**Comment by KelibiaPort** [comment]
OK thanks. 
I will make a try for deltaspike scheduler. I was thinking also to try the quartz integration.

**Comment by mstahv** [comment]
I'll close this now, but if there appears a sweet spot for some helper, I'm happy to work with such to Viritin.
