### ISSUE TITLE
process of Saving data but sending null value.

### ISSUE THREAD

**Issue by mortoza** [viritin/viritin#94]
Hi
I am user viritin, it had been working well but recently i have been encountering error in saving the data in table Country:

In this example, the error i see is as follows:

Internal Exception: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot insert the value NULL into column 'ID', table 'inteaccGms.dbo.COUNTRY'; column does not allow nulls. INSERT fails.
Error Code: 515
Call: INSERT INTO COUNTRY (ID, NAME) VALUES (?, ?)
	bind => [2 parameters bound]
Query: InsertObjectQuery(com.inteacc.entity.Country@143adb5d)
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:331)

The entity file Country is as follows: 
@Entity
public class Country implements Serializable {
    @Id
    private String Id;
    private String Name;
    public Country() {
    }

The form contains both ID and Name fields, even i enter ID and name, it returns the error, as being the field is empty. Thanks for your help:

public class CountryV2Form extends AbstractForm<Country> {

    @Inject
    CountryService service;
    
    TextField Id = new MTextField("Id");

    TextField Name = new MTextField("Name");

    @Override
    protected Component createContent() {

        setStyleName(ValoTheme.LAYOUT_CARD);

        return new MVerticalLayout(
                new Header("Edit Country").setHeaderLevel(3),
                new MFormLayout(
                        Id,
                        Name
                ).withFullWidth(),
                getToolbar()
        ).withStyleName(ValoTheme.LAYOUT_CARD);
    }

    @PostConstruct
    void init() {
        setEagerValidation(true);
        setSavedHandler(new SavedHandler<Country>() {

            @Override
            public void onSave(Country entity) {
                try {
                    service.saveOrPersist(entity);
                    saveEvent.fire(entity);
                } catch (EJBException e) {
                    /*
                     * The Entity object uses optimitic locking with the 
                     * version field. Notify user the editing didn't succeed.
                     */
                    Notification.show("The record was concurrently edited "
                            + "by someone else. Your changes were discarded.",
                            Notification.Type.ERROR_MESSAGE);
                    refrehsEvent.fire(entity);
                }
            }
        });
        setResetHandler(new ResetHandler<Country>() {

            @Override
            public void onReset(Country entity) {
                refrehsEvent.fire(entity);
            }
        });
        setDeleteHandler(new DeleteHandler<Country>() {
            @Override
            public void onDelete(Country entity) {
                service.deleteEntity(getEntity());
                deleteEvent.fire(getEntity());
            }
        });
    }

    @Override
    protected void adjustResetButtonState() {
        getResetButton().setEnabled(true);
        getDeleteButton().setEnabled(getEntity() != null);
    }

    /* "CDI interface" to notify decoupled components. Using traditional API to
     * other componets would probably be easier in small apps, but just
     * demonstrating here how all CDI stuff is available for Vaadin apps.
     */
    @Inject
    @CountryEvent(CountryEvent.Type.SAVE)
    javax.enterprise.event.Event<Country> saveEvent;

    @Inject
    @CountryEvent(CountryEvent.Type.REFRESH)
    javax.enterprise.event.Event<Country> refrehsEvent;

    @Inject
    @CountryEvent(CountryEvent.Type.DELETE)
    javax.enterprise.event.Event<Country> deleteEvent;
}

**Comment by mstahv** [comment]
You seem to be using non standard property names (Id instead of id). This is just a guess, but maybe that disturbs the naming based data binding? You could try changing to property names with non-capital first letter or explicitly defining the bound property with PropertyId annotation.

**Comment by mortoza** [comment]
Thank you, might be, but I am suddenly stuck with running vaadin in Netbeans. Encountering problem in compiling widgetset, cant test this until this widgetset problem is resolved.

regards
Mortoza

**Comment by mstahv** [comment]
I assume this was a naming issue and close this for now.
