### ISSUE TITLE
Suggest adding "withFullExpansion()"

### ISSUE THREAD

**Issue by cbmeeks** [viritin/viritin#99]
Instead of always using

    .withFullHeight()
    .withFullWidth()

Why not combine the two and have

    .withFullExpansion()

In fact, take it a step further and have

    .withFullExpansion("propertyId")

So that not only does it fully expand in width and height, but it also calls "expand" on "propertyId".

**Comment by mstahv** [comment]
Not sure if I'd mix actual component sizing with column expansion. Do you mean withFullExpansion would be like existing

    public MTable<T> expand(String... propertiesToExpand)

, but with calls to withFullWidth and withFullHeight?

If we'd add withFullSize() method, your use case would be configured like this:

   table.withFullSize().expand("name");

Let me know what you think.

**Comment by mstahv** [comment]
Looking at the related pull request https://github.com/viritin/viritin/pull/101/commits from you, it only contains width expansion, which makes more sense...

**Comment by mstahv** [comment]
There is no expandFirstColumn() method as per discussion in pull #101
